### ISSUE TITLE
Color comparison allocates memory in 0.3

### ISSUE THREAD

**Issue by cstjean** [JuliaGraphics/Colors.jl#14]
```julia
const transparent_color = RGBA{Ufixed8}(0.0,0.0,0.0,0.0)
function count_trans(arr)
    out::Int = 0
    for a in arr
        if a == transparent_color out += 1 end
        #if a.r == transparent_color.r && a.g == transparent_color.g && a.b == transparent_color.b
        #    out += 1 end
    end
    out
end
arr = fill(transparent_color, 1000000)
@time count_trans(arr)
> elapsed time: 0.031248975 seconds (12273160 bytes allocated)
```
The commented out version allocates 33 KB. The work-around is easy for me, so I'm not asking for a fix, more of a FYI. Is that useful? I need to bite the bullet and figure out how to contribute soon, I think I can  fix that myself.

If it's fixed in 0.4 it might push me to upgrade before the release.

**Comment by timholy** [comment]
I can verify the allocation on 0.3. Doesn't allocate on 0.4:
```jl
julia> @time count_trans(arr)
  0.002282 seconds (5 allocations: 176 bytes)
1000000
```

I'm sure it's fixable on 0.3, but upgrading is a good idea anyway.

**Comment by cstjean** [comment]
Ok, thank you for checking!
