### ISSUE TITLE
Broken distinguishable_colors 

### ISSUE THREAD

**Issue by axsk** [JuliaGraphics/Colors.jl#16]
When allowing for high luminances it produces undistinguishable colors :( 

```
using Colors
Colors.distinguishable_colors(8, lchoices=linspace(0, 255, 5))
```
![image](https://cloud.githubusercontent.com/assets/5798790/9916410/7cc4c332-5cbc-11e5-93c6-ad73b873771b.png)

In comparison the behaviour from the old Color.jl package.
```
using Color
Color.distinguishable_colors(8, lchoices=linspace(0, 255, 5))
```
![image](https://cloud.githubusercontent.com/assets/5798790/9916373/5592f720-5cbc-11e5-8435-f354f6ba33d8.png)

Happens with both, Colors release and master.

**Comment by axsk** [comment]
Reading further I realized that in LCH the luminance is defined to be in [0,100], 
so I screwed this up :/
Comparing again ``` Colors.distinguishable_colors(8) ```
![image](https://cloud.githubusercontent.com/assets/5798790/9916788/865d1a6e-5cbe-11e5-8b3d-fff6a7f60a2d.png)
with  ``` Color.distinguishable_colors(8) ``` 
![image](https://cloud.githubusercontent.com/assets/5798790/9916773/73279fc8-5cbe-11e5-9f65-66a8c6a6c0cb.png)
made me wonder though why yellow is skipped in favour of a third blue in the new version...

Well, it's not broken so feel free to close this.

**Comment by axsk** [comment]
Oh, would we maybe have some space for fixed color palettes like [these](http://captainmeta.tumblr.com/post/91055782276/colortables-for-scientific-visualization)?

**Comment by timholy** [comment]
The difference between the old and new is that it performs the computations in LCHab space in the new one; it constantly converts between RGB and LCHab in the old one. There could, of course, be a bug; you could `@show` the color differences between candidates you like and the ones it chooses, if you feel like diving into this.

**Comment by timholy** [comment]
I'd be fine with having some fixed palettes. There's a ColorBrewer package already, interestingly. Not really my expertise, so others should chime in.

**Comment by axsk** [comment]
Correct me if I'm wrong, but increasing the desired number of colors just adds new colors to the palette and doesn't change the already obtained. I wonder if it possible to obtain the really maximally distinguishable colors. Shouldn't I have to move all colors when adding a new one?

The simple picture in my head is that of a circle. When choosing n points with maximal distance I divide it into equally large sectors, but this requires changing multiple points when increasing n.

**Comment by timholy** [comment]
Correct. This package produces the nth distinguishable color as the one "farthest" from the first n-1. It does not reconsider the first n-1 in light of the chosen value for the nth.

Another algorithm would, of course, make a fine contribution. Would be interesting to compare performance.
