### ISSUE TITLE
Supporting addition/averaging in color spaces other than RGB

### ISSUE THREAD

**Issue by jiningq** [JuliaGraphics/Colors.jl#23]
According to this question
http://stackoverflow.com/questions/649454/what-is-the-best-way-to-average-two-colors-that-define-a-linear-gradient
it seems LAB is the most appropriate space to do color averaging in. Yet it seems averaging isn't supported in that space. I'm wondering whether we can add support for that.

Or, this could possibly be very silly, is there a way I can access the color coordinate of type LAB so I can do operations on these numeric values directly.

I submitted this issue under the Color package as well but it seems this package is maintained more frequently. Please close the duplicates if necessary.

**Comment by timholy** [comment]
@jiningq, see the type definition [here](https://github.com/JuliaGraphics/ColorTypes.jl/blob/792dfee18016cdb77c56e0cbff4d0262e4e7779d/src/types.jl#L181-L186); you can access members the usual way, e.g., `c.l`. But there's also `weighted_color_mean` (see the help), which should do what you want already.

**Comment by jiningq** [comment]
Thanks!
I was being foolish...

Have a good night.
