### ISSUE TITLE
Question: Interface for external colormaps?

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Colors.jl#243]
Would it make sense to have a general interface to colormaps via Colors? So to have in Colors something like: register_colormap(cname, function) that attaches a function to create colormaps (like 'jet') to the Colors API, so that colormap('jet',64) produces something?

**Comment by timholy** [comment]
I confess to not having thought about (or really, used) colormaps much; maybe people who have done this could comment?

**Comment by stevengj** [comment]
Good colormaps are important and difficult; see e.g. this video on the design of a new default colormap for Matplotlib: https://youtu.be/xAoljeRJ3lU

One option would be to just have a Colormaps package that exports a `colormap(name, N)` function to return an array of colors, and would come built-in with all of the Matplotlib ones (which are free to repackage).

**Comment by lobingera** [comment]
@stevengj, i think i have a deja vu, and you answered my same question already...

It's like this, Colors.jl provides a colormap function (and deals with a lot of other color issues), so it would be nice, that to get a colormap (with certain parameters and beyond just the number) to reuse the API. This would simplify a few things (for programmers of plotting packages etc.). I agree with you on the data part, this can be done in another package to provide fixed, known colormaps and functions that create colormaps.
