### ISSUE TITLE
Viridis colormap in Colors.jl

### ISSUE THREAD

**Issue by CorySimon** [JuliaGraphics/Colors.jl#245]
`colors = colormap("Blues", 10)` is very useful for Gadfly, but it requires a non-white background for my plots for when the color is white.
As a feature request, it would be great to have the new Viridis colormap in Colors.jl that maps a scalar value between 0 and 1 to a color!

https://bids.github.io/colormap/

**Comment by tbreloff** [comment]
See for reference: https://github.com/tbreloff/Plots.jl/issues/185

**Comment by stevengj** [comment]
See also #243.   I think it would be useful to have a Colormaps package that just provides all of the Matplotlib colormaps.

**Comment by stevengj** [comment]
But you're right that since we have a `colormap` function with a few colormaps already in Colors, in the short run we should probably provide viridis.

**Comment by CorySimon** [comment]
@stevengj Yes, and since a lot of research went into Viridis to make a scientific colormap, it would be great to at least have this [assumingly superior over others] colormap in Colors.jl. Most scientific journals do not allow gray backgrounds in plots, so I am stuck right now with Gadfly. One cannot see the white curve with a white background:

![default](https://cloud.githubusercontent.com/assets/4196261/14690656/edded360-0701-11e6-8e7b-b0b9eca2a863.png)

**Comment by lobingera** [comment]
Actually your question falls into two domains: How a julia infrastructure provides standard colormaps. But viridis (and similar cases) is for image mapping or similar. Your grey on white problem should be addressed with distinguishable_colors

**Comment by CorySimon** [comment]
@lobingera distinguishable_colors will not suffice for my data visualization. I not only need to distinguish the curves in my plot, which each correspond to a different $\epsilon$, but also to intuitively show the *progression* from a low to high $\epsilon$, as I did here with shades of green.

**Comment by tbreloff** [comment]
To be clear... there are really two separate interface issues here:

- How to create a list of N colors given some input (colormap name, or distinguishable colors, etc)
- How to interpolate arbitrary colors from that "vector of colors".

Depending on your application, you may use the term "colormap" to refer to either of these functions.  It's important to distinguish.

I know there's the method `colormap` in Colors.jl, and that would be good to use as the base method to override, but is there also an existing method/interface for the second functionality?

I have a version of both in Plots, and the `Plots.ColorGradient` encompasses both functions... storing/building a vector and interpolating with potentially warped views of the colors.  I'd like to move this to Colors, but I feel like there's a ton of code and I'm not sure how to start the transfer.  Any opinions would be appreciated.

**Comment by tbreloff** [comment]
> One cannot see the white curve with a white background

You could consider adjusting your colormap using something like https://github.com/tbreloff/Plots.jl/blob/master/src/colors.jl#L212-L229

**Comment by briochemc** [comment]
I guess this was solved through [ColorSchemes.jl](https://github.com/JuliaGraphics/ColorSchemes.jl)? Viridis and all of matplotlib's colormaps are available ([see docs](https://juliagraphics.github.io/ColorSchemes.jl/stable/basics/#matplotlib)). Should this be closed?

**Comment by kimikage** [comment]
I am not quite sure what the OP's "real" issue is, but since there has been no response for a long time, I will close this issue.
