### ISSUE TITLE
Starting a ColorMaps package

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Colors.jl#246]
Hello colleagues,

i'd like to take the initiative and start a color maps package with the scope:

- provide standard colormaps (i.e. jet, matplotlib options A ...D, other 'know' industry standards)
- code to construct colormaps (from parameters or constraints)

@tbreloff already offered the possibility to inherit code that is actually in Plots.jl right now.
And from my perspective other code from e.g. Colors.jl could be moved there also.

Could someone from the Group please raise my permissions, so i can directly start the repository under JuliaGraphics?

**Comment by tbreloff** [comment]
I think, if well done, that this is a good idea. Would distinguishable_colors and similar functions be moved there? Would it be expected that NoveltyColors.jl, ColorBrewer.jl, and other similar packages be reworked to extend ColorMaps.jl?

As I said, I'd like to contribute to this package, partly just to ensure it will support Plots. 

We should decide early on what the core interface/types will look like. I'm happy with the ColorVector/ColorGradient types in Plots. I think the getColor/getColorZ method could be renamed or replaced... Possibly just by overriding setindex. In general, it's nice to support a type abstraction where single colorants, functions, vectors, and infinite gradients have the same methods implemented... Then you can just ask for a color, without caring what is generating that color. 

Also, it's important to be able to support optional overrides of the alpha channel, though I think my current method of "color or nothing" should be replaced with something type-stable (Nullable{Float64}?)

Much of this may be implemented already in Colors or elsewhere and I just don't realize. 

Thoughts?

**Comment by lobingera** [comment]
i started something locally (already called ColorMaps) and include the matplotlib option a-d data and my code for cubehelix. Do we discuss about necessary API here, or shall i go public with the package first

**Comment by tbreloff** [comment]
@lobingera when you say "go public", I assume you mean making the repo public, not registering with METADATA?  If so, then please do!  It's easier to comment on actual code.

**Comment by lobingera** [comment]
Well, there's not much code today...

**Comment by tbreloff** [comment]
Only one way to change that ;)

**Comment by lobingera** [comment]
You seem to be right!

**Comment by lobingera** [comment]
https://github.com/lobingera/ColorMaps

**Comment by tbreloff** [comment]
Does the repo need to be https://github.com/lobingera/ColorMaps.jl?

**Comment by lobingera** [comment]
well, i do not have that many rights to open repostiories beyond my own accout...

**Comment by kmsquire** [comment]
I think he just meant that you should add .jl to the name... :-)

**Comment by lobingera** [comment]
i changed.
