### ISSUE TITLE
distinguishable_colors for ColorAlpha?

### ISSUE THREAD

**Issue by tlnagy** [JuliaGraphics/Colors.jl#250]
I'm trying to fix a bug in Gadfly (dcjones/Gadfly.jl#844) and one of things I'm running into is the lack of a `distinguishable_colors` for the `ColorAlpha` type:

``` julia
ERROR: MethodError: no method matching distinguishable_colors(::Int64, ::Array{ColorTypes.RGBA{Float64},1})
Closest candidates are:
  distinguishable_colors(::Integer; kwargs...) at /Users/tamasnagy/.julia/v0.5/Colors/src/colormaps.jl:86
  distinguishable_colors{T<:ColorTypes.Color{T,N}}(::Integer, ::AbstractArray{T<:ColorTypes.Color,1}; transform, lchoices, cchoices, hchoices) at /Users/tamasnagy/.julia/v0.5/Colors/src/colormaps.jl:39
  distinguishable_colors(::Integer, ::ColorTypes.Color{T,N}; kwargs...) at /Users/tamasnagy/.julia/v0.5/Colors/src/colormaps.jl:85
```

Would it enough to store the transparency values, run `distinguishable_colors` and add the transparency values back in?

**Comment by timholy** [comment]
I'm not even sure what it would mean to have the alpha channel participate in any notion of distinguishability---if you draw a transparent red on top of itself several times, it becomes more red, and consequently isn't very distinguishable from full red.

So adding the alpha after running the opaque version of the algorithm seems to make sense, and at the moment I can't see any justification for those receiving *different* alpha values from one another. If they are different, which values do you assign to the newly-generated colorants?

**Comment by tlnagy** [comment]
> If they are different, which values do you assign to the newly-generated colorants?

What is they in this context? 

I'm starting to doubt that I would need to call `distinguishable_colors` here. Since this is full manual color mode, it might be better to simply trust the user to use distinguishable colors and not enforce it.

**Comment by timholy** [comment]
they = the different alpha values in the seed-vector that you pass into `distinguishable_colors`.

**Comment by tlnagy** [comment]
Ah, I see what you mean. Assign the alpha values to the new color most resembling the color they belong to in the seed-vector?

**Comment by timholy** [comment]
To me, that sounds like behavior that the user won't be able to predict without a careful read of the documentation. On balance I think I prefer the MethodError, as I just don't think it makes much sense to talk about distinguishability in the context of an alpha channel.

Can't you call `map(color, seed)` from Gadfly and then re-add whatever alpha channel makes you happy?

**Comment by tlnagy** [comment]
The `MethodError` is unfortunate though. Currently, when trying to use your own set of colors to `Scale.color_discrete_manual`, `distinguishable_colors` is always applied to the input. I guess one solution would be to not run the `distinguishable_colors` function if RGBA values are supplied.

**Comment by timholy** [comment]
I'd be fine with an informative error message.

**Comment by tlnagy** [comment]
Is that the best behavior though? You want to use some RGBA values in your plot and Gadfly errors out and tells you that you can't give alpha values? That seems a bit strict.

**Comment by tlnagy** [comment]
Note: I'm changing what I'm saying here. I don't think we should make any changes to `Colors.jl`, only that I shouldn't call `distinguishable_colors` when the user supplies RGBA values to the manual plot coloring function in Gadfly.

**Comment by timholy** [comment]
Right, I'm saying handle RGBA from the Gadfly side, since there's no obviously correct behavior in general. It would be fine to define a `distinguishable_colors` method here that gives an informative error message, though.

**Comment by kimikage** [comment]
xref: PR #439

**Comment by kimikage** [comment]
![Uploading DSC_0390.JPG…]()
