### ISSUE TITLE
unexpected results inconvert RGB -> [DIN99d,DIN99dA,ADIN99d] -> RGB

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaGraphics/Colors.jl#256]
Normally, I would expect that the conversion `c1::TypeA` -> `c2::TypeB` -> `c3::TypeA` yields that `c1` is approximately equal to `c3`. However for the types above one gets

``` julia
julia> convert(RGB,convert(DIN99d,RGB(1,0.5,0)))
RGB{Float64}(0.5618900556828353,0.660676085072947,0.6265900923320097)

julia> convert(RGBA,convert(DIN99dA,RGBA(1,0.5,0,0.4)))
RGBA{Float64}(0.5618900556828353,0.660676085072947,0.6265900923320097,0.4)
```

which suggests, that there is a problem with the conversion `RGB`<->`DIN99d`.

**Comment by m-lohmann** [comment]
I implemented DIN99 and DIN99o back then... I’ll have a look at the DIN99d conversion.

**Comment by hofmannmartin** [comment]
thank you very much

**Comment by m-lohmann** [comment]
I thought I already had. Something must have gone wrong. I'll make a pull request as soon as I can.
