### ISSUE TITLE
convert RGB{Float16} -> HSI sometimes fails

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaGraphics/Colors.jl#257]
most of the time there is no problem, but if I try to convert `RGB{Float16}(0.9473,0.962,0.9766)` to `HSI` I run into an DomainError.
```julia
convert(HSI,RGB{Float16}(0.9473,0.962,0.9766))
ERROR: DomainError:
 in cnvt(::Type{ColorTypes.HSI{Float16}}, ::ColorTypes.RGB{Float16}) at ~/.julia/v0.5/Colors/src/conversions.jl:258
 in convert(::Type{ColorTypes.HSI}, ::ColorTypes.RGB{Float16}) at ~/.julia/v0.5/ColorTypes/src/conversions.jl:7
```

This Error does not occur if `Float32` or `Float64` is used instead of `Float16`. Furthermore the Error just occurs for some `RGB` values and not for all. This behaviour seems odd to me.

**Comment by timholy** [comment]
The problem is the argument of the `sqrt` in that `cnvt` method is negative if you use `Float16`, but it's positive otherwise. It might take some digging to figure out the right thing to do in such cases.

**Comment by timholy** [comment]
See #258

**Comment by hofmannmartin** [comment]
Thank you for the quick fix.
