### ISSUE TITLE
Example sequential_palette 

### ISSUE THREAD

**Issue by cpierard** [JuliaGraphics/Colors.jl#265]
Hello,

I'm having some troubles generating a sequential_palette for a heat map. The documentation is not clear to me. Can someone provide me with a working example of sequential_palette and diverging_palette? Can I use this with a heatmap in Plots.jl? 

```julia
sequential_palette(h, [N::Int=100; c=0.88, s=0.6, b=0.75, w=0.15, d=0.0, wcolor=RGB(1,1,0), 
dcolor=RGB(0,0,1), logscale=false])

diverging_palette(h1, h2 [, N::Int=100; mid=0.5,c=0.88, s=0.6, b=0.75, w=0.15, d1=0.0, d2=0.0,
 wcolor=RGB(1,1,0), dcolor1=RGB(1,0,0), dcolor2=RGB(0,0,1), logscale=false])
```

**Comment by cormullion** [comment]
I once had a go at writing [some basic docs for Color(s).jl.](https://github.com/JuliaArchive/Color.jl/blob/455196e2f144f2c256d37c46648ec45b23cc0c97/README.md). Perhaps there's a bit there that's still useful?

For Plots.jl, you can use some tools in [PlotUtils](https://github.com/JuliaPlots/PlotUtils.jl) to build gradients from color lists -- `cgrad` perhaps?
