### ISSUE TITLE
Function or constructor to convert hex to Color object?

### ISSUE THREAD

**Issue by tlnagy** [JuliaGraphics/Colors.jl#267]
Is there any reason* that there isn't an inverse function for `hex`? That is, a way to convert hex triplets to a Color object. Something like:

```
Color("#7aa457")
```

or 

```
Color(ihex("#7aa457"))
```

*A reason other than no one has implemented it. I ask because there might be some problems associated with the hex codes that I'm unaware of.

**Comment by tlnagy** [comment]
Actually I see now that Colorant can parse hex triplets:

```
typeof(colorant"#7aa457")
```
is `ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}}`

**Comment by timholy** [comment]
Any reason not to close this? What more does it need? Mention in the docstring for `hex`?

**Comment by tlnagy** [comment]
Yeah, I think a simple doc update should be enough to close this. I was thinking that it might be good to mention hexadecimal or hex triplet when `colorant` is introduced in the readme or in the docs for `colorant`.

**Comment by timholy** [comment]
Would love to see a PR, then.
