### ISSUE TITLE
Julia 0.6 TODO: write awesome promotion rules

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Colors.jl#273]
Between ColorTypes and #272, we have some useful but imperfect promotion rules that I propose to fix once we can rely on the awesome new type system. Here's one simple example of current failings:

```julia
julia> using ColorTypes

julia> promote_type(RGB1{Float32}, RGB1{Float32})
ColorTypes.RGB1{Float32}

julia> promote_type(RGB1{Float32}, RGB1{Float64})
ColorTypes.RGB{Float64}
```

This behavior is a consequence of [these rules](https://github.com/JuliaGraphics/ColorTypes.jl/blob/a846a5327a683c1fadb0fa400155d2635eb21b8f/src/conversions.jl#L1-L2). The ideal way to write this would be to separately promote the "inner" type (`Float32` or `Float64`) and the "outer" type (e.g., `RGB1{<:Fractional}`). I suffered through doing something similar with conversion (e.g., `convert(RGB, c)` without specifying the "inner" type) on julia 0.4, and it wasn't fun: getting the dispatch working properly for types with only a typevar inner type was basically black art and strongly dependent on the order of function definitions. I basically don't have the time/patience to do this again. But once we can rely on the new type system, this should be much more pleasant.

**Comment by kimikage** [comment]
Can they move to `ColorTypes.jl`? (https://github.com/JuliaGraphics/Colors.jl/pull/320/commits/0646395e1b8adb53b854a698990d783611fb5255)
https://github.com/JuliaGraphics/Colors.jl/blob/0ceb396d38c3a0577110a3b50623dd5de5916d09/src/Colors.jl#L9-L11
https://github.com/JuliaGraphics/Colors.jl/blob/5d6f18aa45904d089f55654c1139d7faf7ea441f/src/promotions.jl#L1-L6

**Comment by timholy** [comment]
Those seem like reasonable candidates for moving.

**Comment by kimikage** [comment]
Bump.
https://github.com/JuliaGraphics/ColorTypes.jl/issues/129
https://github.com/JuliaGraphics/ColorTypes.jl/pull/164

**Comment by kimikage** [comment]
I wrote awful promotion rules in ColorTypes.jl on Julia **1.3** (cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/170). :smile:
The rules will take effect in the next release.

**Comment by timholy** [comment]
They're beautiful, not awful. Though I know exactly what you mean. So glad to have this fixed!
