### ISSUE TITLE
Bradford transformation support

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#278]
As `README.md` says, Colors.jl already has a useful function for chromatic adaptation named `whitebalance`.  
`whitebalance` uses the CAT02 transformation matrix to convert colors into LMS.  
However, not only the CAT02 but also the linear Bradford transformation is commonly used in the field of color management because of the interoperability.  
In fact, to minimize the risk of conflict, the Bradford model is recommended in the [ICC specification](http://www.color.org/specification/ICC1v43_2010-12.pdf).

We can obtain the adaptation result in the Bradford model by converting the colors into LMS with the Bradford transformation in advance of calling `whitebalance`, and converting the result back into the original color space.
I think it's too much bother to do that every time, though.

A simple solution is to add a new function such as the following:

```julia
# the Bradford transformation matrix from v4 ICC Specification
const BFD = [ 0.8951  0.2664 -0.1614
             -0.7502  1.7135  0.0367
              0.0389 -0.0685  1.0296 ]
const BFD_INV = inv(BFD)

function bradford{T <: Color}(c::T, src_white::Color, ref_white::Color)
    c_xyz = convert(XYZ, c)
    src_xyz = convert(XYZ, src_white)
    dest_xyz = convert(XYZ, ref_white)
    
    c_lms = BFD * [c_xyz.x, c_xyz.y, c_xyz.z]
    src_wp = BFD * [src_xyz.x, src_xyz.y, src_xyz.z]
    dest_wp = BFD * [dest_xyz.x, dest_xyz.y, dest_xyz.z]
    ans = BFD_INV * (c_lms .* dest_wp ./ src_wp)

    convert(T, XYZ(ans[1], ans[2], ans[3]))
end
```
But I don't know whether it makes sense to propose such an ad-hoc function.  

Another solution is to make changes to `cnvt{T}(::Type{LMS{T}}, c::XYZ)` and `whitebalance` to take the CAT matrix as an optional argument.  

Do you have any ideas?

**Comment by m-lohmann** [comment]
I have been thinking about implementing the handful of most important CATs a while ago, including the BFD (linear or non-linear), simple vonKries etc.

As far as I remember CAT02 is basically the BFD, but I might be wrong.

The problem is that there is no strict color conversion pipeline enforced in the whole package.
Another problem is that RGB is not strictly enforced to be a device color space with potentially negatve values for later processing etc.
I was quitce swamped in a lot of other stuff so I lost track of the whole thing. I wanted to take a deeper look into it because the lack of all this e.g. leads to problems in the DIN99d color space conversions.

Yes, optional arguments would be a good idea in my eyes.

Optional arguments in the whole RGB use as well, to define e.g. if it’s sRGB, ARGB or a different RGB color space, for potentiall necessary Gamut compression. Just clipping negative RGB values or values above 1 is pretty much the worst idea in color metrics.

**Comment by kimikage** [comment]
I'm in favor of the `adaptation()`, though there is room for consideration of the name and order of arguments.

**Comment by kimikage** [comment]
The time passed while I was waiting for Julia v1.x and its packages to be stable.

I'm going to implement `adaptation()` by taking the following steps.
1.  Add the white point support for all conversions from/to XYZ.
2. Extend conversion from/to LMS
 2.1 Add types for represent CAT.
 2.2. Add core conversion functions: `xyz_to_lms()` and `lms_to_xyz()`.
 2.3. Add `convert()`s which wraps the core conversion functions.
3. Add `adaptation()`.
4. Add tests and docs.

**Comment by kimikage** [comment]
## About step 1
Current `whitebalance()` has a problem with the [pre-](https://github.com/JuliaGraphics/Colors.jl/blob/e08950fe9e24a5848d408c3576d6ebf275f4e435/src/algorithms.jl#L36)/[post-](https://github.com/JuliaGraphics/Colors.jl/blob/e08950fe9e24a5848d408c3576d6ebf275f4e435/src/algorithms.jl#L48)conversions which depend on the white points.
For example, a `Lab` color should be converted to `LMS` via `XYZ` with `src_white`, and the adapted `LMS` color should be converted to `Lab` via `XYZ` with `ref_white`.
However, there is no general option to pass the white point to `convert()`, and it results in wrong usage of WP_DEFAULT.

Another related problem is that the `Lab`/`Luv`-based color types, i.e. `LCHab`, `LCHuv`, `DIN99` and `DIN99o`, have no direct path for converting with the white point.

To simplify the codes, it might be a good idea to add the interface to support the white point for _all_ conversions from/to XYZ, including from RGB to XYZ and so on.
In this idea, the following types of fallbacks may be useful:
```julia
convert(::Type{C}, c, wp::XYZ) where {C<:Color} = cnvt(C, c)
cnvt(::Type{XYZ{T}}, c, wp::XYZ) where {T} = cnvt(XYZ{T}, c)
```
But I'm afraid of the outbreak of ambiguity error.
Are the fallbacks safe?
Is it ok not to specify or restrict the type of `c`? (cf. [this](https://github.com/JuliaGraphics/Colors.jl/blob/e08950fe9e24a5848d408c3576d6ebf275f4e435/src/conversions.jl#L301-L316))
What should I do to test the complicated conversion chains?

**Comment by kimikage** [comment]
[WIP] https://github.com/JuliaGraphics/Colors.jl/compare/master...kimikage:cat

**Comment by kimikage** [comment]
## About step 2-3

Let's decide the function name!

- cat
    - :smile_cat: short
    - :crying_cat_face: kitty? catenate?
- adapt
    - :smile_cat: short
    - :crying_cat_face: confusing with adopt
- adaptate
    - :smile_cat: verb
    - :crying_cat_face: uncommon
- adaptation
    - :smile_cat: agrees with technical term
    - :crying_cat_face: noun
- coloradapt
    - :smile_cat: analogous to colordiff
    - :crying_cat_face: long, not readable
- whitebalance
    - :smile_cat: backward-compatible in interface
    - :crying_cat_face: breaking change in behavior
- chromatic_adaptation
    - :smile_cat: exact term
    - :crying_cat_face: too long
- (other)


Then, let's decide the function or method interfaces.

- `adaptation(c, src_white, ref_white, cat)`
    - This is simple and analogous to `whitebalance`.
- `adaptation(c, src_white, ref_white; cat=default)`
    - This is analogous to `colordiff` (v0.9.6) and `whitebalance`.
    - What is good for the default cat? CAT_02?
- `adaptation(c; src_white=def_src, ref_white=def_ref, cat=default)`
    - This is useful for broadcasting.
    - `adaptation(something, src_white=Color.WP_D65, ref_white=Color.WP_D50, cat=CAT_BFD())` is tedious.
    - What are good for the default white points?
- `adaptation(c; src_white=def_src, ref_white=def_ref, cat=default)` where CAT object holds the default white points
    - This is useful for broadcasting.
    - It is a bother to implement (new) CATs. 
    - This may have overhead. (needs benchmarking)
    - Who needs such a high-level interface? The experts may not need the _information hiding_.

**Comment by kimikage** [comment]
## About step 4

Although I can write tests for the behavioral specifications such as the round-trip testing or type checking, for the quantitative testing, the numerical and concrete examples from credible sources are needed.
What should I refer to?

**Comment by KelSolaar** [comment]
What you are doing here is really **Von Kries** chromatic adaptation, the HVS has three recognised types of adaptation: light, dark and chromatic. The two formers are rarely modelled but who knows :) I would at least go for `chromatic_adaptation` and for completeness I would add it is a **Von Kries** type. To give you an example as why it could be useful, we have the following definitions in [Colour](https://github.com/colour-science/colour/tree/develop/colour/adaptation):

- `colour.adaptation.chromatic_adaptation_VonKries`
- `colour.adaptation.chromatic_adaptation_Fairchild1990`
- `colour.adaptation.chromatic_adaptation_CMCCAT2000`
- `colour.adaptation.chromatic_adaptation_CIE1994`

and a wrapper at the top API namespace where you can choose between the 4 methods:

- `colour.chromatic_adaptation`

**Comment by johnnychen94** [comment]
About the interface, I think supporting broadcasting is important. FYI, in https://github.com/JuliaGraphics/Colors.jl/pull/338 changes the API of `colordiff` from style "2." to "3.".

As for names, `CAT` really isn't a good choice IMO; since only developers and maintainers will use `CAT` (If I understand it right), it's okay to keep it long and explicit. Perhaps `AbstractAdaptation`?

Also, I think it's better to be `LinearCAT`(instead of `MatrixCAT`) vs `NonLinearCAT` 😄

**Comment by kimikage** [comment]
> What you are doing here is really Von Kries chromatic adaptation

As you (@KelSolaar) have mentioned, the current `whitebalance` and the very function what **I need** (i.e. linear Bradford transform) are based on Von Kries model.
However, I feel the need to enhance the interface for supporting general transform models.
Thank you for the information about Colour.

**Comment by KelSolaar** [comment]
@kimikage : Complex chromatic adaption models have much more inputs, e.g. **CMCCAT2000**:

```
    XYZ : array_like
        *CIE XYZ* tristimulus values of the stimulus to adapt.
    XYZ_w : array_like
        Test viewing condition *CIE XYZ* tristimulus values of the whitepoint.
    XYZ_wr : array_like
        Reference viewing condition *CIE XYZ* tristimulus values of the
        whitepoint.
    L_A1 : numeric or array_like
        Luminance of test adapting field :math:`L_{A1}` in :math:`cd/m^2`.
    L_A2 : numeric or array_like
        Luminance of reference adapting field :math:`L_{A2}` in :math:`cd/m^2`.
    surround : CMCCAT2000_InductionFactors, optional
        Surround viewing conditions induction factors.
```

**Comment by kimikage** [comment]
> Complex chromatic adaption models have much more inputs

Yes. So I'm going to pass the buck to input CAT object. Not `Type` but CAT `struct` object is passed into the last argument `cat`. This is an analogy to `colordiff`.

**Comment by kimikage** [comment]
@johnnychen94, I also think supporting broadcasting is important. On the other hand, I don't think it is a fatal problem for users to write the wrapper functions or lambdas, though.
> FYI, in #338 changes the API of `colordiff` from style "2." to "3.".

Exactly. I edited the former comment (but I don't know if it is comprehensible enough).

I think `AbstractCAT` is good for the alternative if its subtypes end with `CAT`. :smile_cat:
I purposely chose `MatrixCAT` (instead of `LinearCAT`) because the relationship between them and `NonLinearCAT`s will [not so simple](https://github.com/kimikage/Colors.jl/blob/afeb94b3ff5b69eceb067df0ed08a8e060e63ef6/src/adaptation.jl#L7-L19).

**Comment by kimikage** [comment]
I will do the step 1 (adding the white point argument), after the cleaning up the conversion methods (issue #354).

And then, what about replacing the `wp::XYZ` to something like `ctx::AbstractConversionContext` instead of the current step 2.3 (adding `convert(::Type{XYZ}, c::LMS, wp::XYZ; cat::AbstractCAT=CAT_02())`)?
The context (which currently I need) is like the following.
```julia
struct ConversionContext <: AbstractConversionContext
    src_wp::XYZ
    dest_wp::XYZ
    cat::AbstractCAT
end
```

In the future, we may add something like `src_flavor`/`dest_flavor` (e.g. "LinearRGB", "AdobeRGB", "BT.709" and "DCI-P3" for `RGB`, "BT.601", "BT.709" and "JFIF" for `YCbCr`) or `src_gamut`/`dest_gamut`. I think it must be a trouble maker, though.

**Comment by kimikage** [comment]
It is not easy to be consistent with the current `convert`, and Colors.jl does not necessarily support chromatic adaptation. So, I will try to find another approach.

**Comment by kimikage** [comment]
"I" have declined to support comprehensive color conversions "in Colors.jl".
However, as mentioned in the OP, the linear Bradford transform is often used, so I'm beginning to feel that `bradford()` is worth adding ad-hoc. After three and a half years, I decided to go back to my origin. :smile:

I'm interested in the CSS Color Module Level 5 API, for which the [First Public Working Draft](https://www.w3.org/TR/2020/WD-css-color-5-20200303/) was released this year. (That's just the beginning of the discussion.)
It is strongly dependent on Lab colors etc. of CSS Color Module Level 4. The Level 4 is still in the Working Draft stage, but the Level 5 seems to be setting the course for the Level 4, IMO. So, the linear Bradford transform is important.
(cf. https://drafts.csswg.org/css-color/#lab-to-rgb)

**Comment by kimikage** [comment]
In the scope of colors, I think there is almost no ambiguity in `bradford` referring to the "bradford transform". However, since Bradford is a name derived from a university, I could not rule out the possibility that it has different meanings in other contexts.
Therefore, there are roughly three possible options.
1. name the function `bradford` and export it
2. name the function `bradford_transform` and export it.
3. name the function `bradford` and do not export it

In general, I think avoiding name collisions is the responsibility of the `using` (`import`ing) side. However, considering that Colors.jl can be used in any technical field within visualization (plotting), and that Colors.jl is used with the `reexport` mechanism, I think 2. is safer.
