### ISSUE TITLE
The 3-digit RGB notation (#rgb) is converted incorrectly

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#280]
According to the [CSS specification](https://www.w3.org/TR/CSS2/syndata.html#value-def-color) or [SVG specification](https://www.w3.org/TR/SVG/types.html#DataTypeColor), the three-digit RGB notation (#rgb) is converted into six-digit form (#rrggbb) by replicating digits, not by adding zeros.

However, the current implementation (v0.7.3) incorrectly interprets the #rgb.
```julia
julia> colorant"#fb0" == colorant"#f0b000" # adding zeros
true

julia> colorant"#fb0" == colorant"#ffbb00" # replicating digits
false
```

This problem may be corrected by changing the scaling factor `16` to `17`.

**Comment by timholy** [comment]
Fixed by #281
