### ISSUE TITLE
Better aspect ratio preservation when displaying as SVG

### ISSUE THREAD

**Issue by rdeits** [JuliaGraphics/Colors.jl#283]
I've noticed some minor weirdness with the aspect ratio of arrays of Colors when displayed as SVG, and I think that some improvement might be possible. The relevant code is here: https://github.com/JuliaGraphics/Colors.jl/blob/master/src/display.jl#L22

The specific set of checks in that code can lead to some very strange edge cases. For example, try creating the following arrays:

```julia
A = zeros(Gray, 9, 10)
B = zeros(Gray, 9, 18)
C = zeros(Gray, 9, 19)
```

Matrix A renders each color as a perfect square, which is great. Matrix B squashes the aspect ratio slightly, so each rectangle is a bit taller than it is wide. Matrix C, however, results in this:

![screen shot 2017-04-06 at 1 40 26 pm](https://cloud.githubusercontent.com/assets/591886/24767884/a1b676aa-1ace-11e7-91d3-2db93a9026db.png)

That is, the resulting array is taller than it is wide, and each rectangle has been dramatically stretched. That seems like the wrong behavior. 

I realize that this is a weird edge case, but it happened to come up in my work, so I figured I'd report it. 

If I may, I'd propose something like the following:

1. compute the natural aspect ratio of the array (`m` / `n`)
1. clamp that aspect ratio to some pre-determined range of values
1. size the rectangles based on that clamped aspect ratio
1. scale the rectangles to obey the min. and max. limits on the output size

If that seems reasonable, I'm happy to work on this myself and submit a PR. 

BTW @Evizero you mentioned something over in https://github.com/JuliaImages/Images.jl/issues/619 about new code to render an image in a table. Is that a proposed replacement for the SVG code here?

**Comment by Evizero** [comment]
(I was talking about https://github.com/JuliaImages/Images.jl/pull/574)

**Comment by rdeits** [comment]
@Evizero got it, thanks!
