### ISSUE TITLE
Colormaps are missing

### ISSUE THREAD

**Issue by chuong** [JuliaGraphics/Colors.jl#297]
Thanks for this great works. One thing I would like to add. As compared to Matlab, there are many missing built-in colormaps. It would be very convenient for users if a similar lists of [Matlab's colormaps](https://au.mathworks.com/help/matlab/ref/colormap.html) is provided in this package.

**Comment by timholy** [comment]
This package is mostly about algorithms; if there's an algorithm that can generate them, I'd certainly consider accepting a pull request to add it.

If it's just a question of adding "constants" (meaning, a lookup table), there are quite a few packages for colormaps already:
- [ColorSchemes.jl](https://github.com/JuliaGraphics/ColorSchemes.jl) (see [colormaps](http://juliagraphics.github.io/ColorSchemes.jl/latest/basics.html))
- [PerceptualColourMaps](https://github.com/peterkovesi/PerceptualColourMaps.jl)
- [ColorBrewer](https://github.com/timothyrenner/ColorBrewer.jl)
- [NoveltyColors](https://github.com/randyzwitch/NoveltyColors.jl)

If you see anything missing, it might be best to consider adding them to any of those other packages.

**Comment by chuong** [comment]
Thanks @timholy. I didn't know these packages providing additional colormaps. It would be great if this information is mentioned in the documentation of Colours.jl package at it is has the highest rank when I did a search for Julia support for colormap.

**Comment by timholy** [comment]
Good idea. Done.

**Comment by waldyrious** [comment]
> Good idea. Done.

For future reference, the relevant commit is ca2e38466.
