### ISSUE TITLE
A way to make distinguishable_colors output darker, for use on white backgrounds?

### ISSUE THREAD

**Issue by ianshmean** [JuliaGraphics/Colors.jl#298]
I like using `distinguishable_colors` with PyPlot, but find that with thin line thicknesses, some of the the colors wash out on a white background (see yellow below). Is there a simple way to weight the process towards darker colors?

```
using PyPlot, Colors
vars = 1:10
cols = distinguishable_colors(length(vars))
plot_cols = map(col->(red(col),green(col),blue(col)),cols)
for i = 1:length(vars)
    plot(1:10,rand(10),"-o",c = plot_cols[i],linewidth=0.5,markersize=1)
end
```
![image](https://user-images.githubusercontent.com/1694067/32179608-3ae2ad1e-bd66-11e7-8ca4-6336f01c7475.png)

**Comment by timholy** [comment]
Supply white as a seed, and then drop it from the returned list of colors:
```julia
julia> distinguishable_colors(3)
3-element Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},1}:
 RGB{N0f8}(0.0,0.0,0.0)  
 RGB{N0f8}(1.0,1.0,0.384)
 RGB{N0f8}(1.0,0.624,1.0)

julia> distinguishable_colors(4, [RGB(1,1,1)])
4-element Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},1}:
 RGB{N0f8}(1.0,1.0,1.0)      
 RGB{N0f8}(0.0,0.0,0.0)      
 RGB{N0f8}(0.757,0.161,0.886)
 RGB{N0f8}(0.82,0.29,0.0)    
```

**Comment by ianshmean** [comment]
Ah, of course, thanks. Perhaps a hint in docs might be helpful, giving the explicit example of use with pyplot?
```
cols = distinguishable_colors(length(variants)+1,[RGB(1,1,1)])[2:end]
pcols = map(col->(red(col),green(col),blue(col)),cols) 
```

**Comment by timholy** [comment]
Could you add that? Just open the file on GitHub and click the pencil icon.

**Comment by ianshmean** [comment]
Done. #299

**Comment by tpapp** [comment]
I am using this so much that I am wondering if a `dropseed` keyword argument could be added.
