### ISSUE TITLE
Drop Graphics dependency

### ISSUE THREAD

**Issue by dcjones** [JuliaGraphics/Colors.jl#3]
I don't know when or how this happened in Color.jl, but it seems really backwards. I guess it's a remnant from when Graphics.jl was in Base. I can do this, but I'll wait till after c-day.

**Comment by timholy** [comment]
I agree totally. I'll just incorporate it into my own changes.

**Comment by timholy** [comment]
Fixed in #5. I'll submit a PR to Graphics shortly.
