### ISSUE TITLE
does mid work on colormap?

### ISSUE THREAD

**Issue by ultradian** [JuliaGraphics/Colors.jl#300]
I was playing with trying to change the midpoint in a colormap and it doesn't work the way I expected.

For example, `colormap("Blues")` generates an array that starts with 
```
 RGB{Float64}(0.958129,0.992733,0.998897) 
 RGB{Float64}(0.948956,0.98958,0.997057)  
 RGB{Float64}(0.939677,0.986361,0.995234) 
```
and goes to
```
 RGB{Float64}(0.0548094,0.182609,0.382798)
 RGB{Float64}(0.0484511,0.169616,0.362331)
 RGB{Float64}(0.0418427,0.156645,0.341597)
```
with midpoint `colormap("Blues")[50]` giving:
`
RGB{Float64}(0.40043042841321896,0.7304593324507547,0.9058502694643216)
`
When I try `colormap("Blues", mid=0.75)[50]` I get the same result.  I thought I should get something different because this point would move to the left.  Do I misunderstand something?

**Comment by timholy** [comment]
Hoping someone who uses colormaps replies here. CC @glenn-sweeney
