### ISSUE TITLE
Change permissions

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Colors.jl#314]
Could someone change the permissions on this repo? I keep accidentally pushing directly to master when I forget to branch...

**Comment by timholy** [comment]
Maybe done? I can't quite tell, here's a screen shot:
![image](https://user-images.githubusercontent.com/1525481/44008290-70eb71cc-9e91-11e8-8074-5474df7bfd1b.png)

**Comment by cormullion** [comment]
Looks good. Protecting me from myself...! :)
