### ISSUE TITLE
Limit for displaying vector of colors in IJulia

### ISSUE THREAD

**Issue by mprat** [JuliaGraphics/Colors.jl#317]
When trying to display large vectors of Colors (for example when you have a long row of pixels from Images.jl) in IJulia, there should be a default limit for when the display gets rendered as a PNG rather than an SVG. For large vectors and slow computers (or computers with not that much RAM), displaying a 1000-point vector in an SVG in IJulia bricks the computer.

**Comment by kimikage** [comment]
The following is not a drastic solution but one of the mitigation measures:
https://github.com/JuliaGraphics/Colors.jl/compare/master...kimikage:display

It is easy to limit the matrix size.
However, I don't think it is a simple matter of what should be displayed.
Top left corner? Four corners?
Decimation?

By the way, I found a little [bug](https://github.com/JuliaGraphics/Colors.jl/commit/dacf8578083bf90d3653cde661106526e0a616b4).

**Comment by kimikage** [comment]
Related issues:
https://github.com/JuliaLang/IJulia.jl/issues/229
https://github.com/JuliaImages/ImageShow.jl/issues/11

**Comment by kimikage** [comment]
Another reduction method was implemented: https://github.com/JuliaGraphics/Colors.jl/pull/346#issuecomment-529076468
