### ISSUE TITLE
Please consider deleting Project.toml

### ISSUE THREAD

**Issue by andreasnoack** [JuliaGraphics/Colors.jl#322]
It is not yet needed as `REQUIRE` is the basis for the registry and, for the time being, the Project.toml file breaks CIBot for all packages that depend on `Colors`. That will be fixed eventually but meanwhile, it would be great if you could remove the project file.

**Comment by timholy** [comment]
I'll ask anyone who has authored or touched that file to chime in here, @staticfloat and @fredrikekre, since they both know more about this stuff than I.

**Comment by staticfloat** [comment]
I’ll let @fredrikekre make the call, as he knows more than I. :P

**Comment by fredrikekre** [comment]
If it simplifies life for JuliaCIBot, which apparently uses the old package manager, I see no reason not to.

**Comment by cormullion** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/17073#issuecomment-414247458 :)

**Comment by cormullion** [comment]
The release number inside the Project.toml file is not the same as the release number in Metadata.

**Comment by cormullion** [comment]
hopefully fixed in v0.9.6
