### ISSUE TITLE
Named colors shouldn't be Tuple{Int64,Int64,Int64}

### ISSUE THREAD

**Issue by scls19fr** [JuliaGraphics/Colors.jl#324]
Hello,

I noticed

```julia
julia> Colors.color_names["indianred"]
(205, 92, 92)

julia> typeof(Colors.color_names["indianred"])
Tuple{Int64,Int64,Int64}
```

that's odd... I wonder why it is not `Tuple{UInt8,UInt8,UInt8}`

maybe a better approach could be to have `RGB{N0f8}` as value in `color_names` dictionnary.

Or provide function to get color as `RGB{N0f8}`

```julia
using Colors
using ColorTypes
using FixedPointNumbers


struct NamedColor
    s::String
end

function RGB{T}(namedcolor::NamedColor) where {T}
    RGB(map(c->reinterpret(T, c), UInt8.(Colors.color_names[namedcolor.s]))...)
end

RGB(namedcolor::NamedColor) = RGB{N0f8}(namedcolor)

namedcolor = NamedColor("indianred")

println(RGB{N0f8}(namedcolor))
println(RGB(namedcolor))
```

Maybe having some other function to return any `RGB{T}` from `NamedColor` should be considered.

Kind regards

**Comment by scls19fr** [comment]
PR submitted.

but maybe this part of doc could be a good place to show how to convert to `RGB{N0f32}` (for example)

but it could also be in https://github.com/JuliaGraphics/ColorTypes.jl

**Comment by scls19fr** [comment]
RGB{N0f32}(colorant"indianred")

**Comment by timholy** [comment]
@scls19fr, why would convert to `RGB{N0f32}`? Do you realize that is 96-bit color? Did you actually mean to convert to `RGB24` by any chance?

**Comment by scls19fr** [comment]
oh yes... that's a bit overkilled

**Comment by scls19fr** [comment]
Given, values in tuples, I'm wondering if

https://github.com/JuliaGraphics/Colors.jl/blob/0f4c744902f22fb73776e50e839a2bf8ebfdc9d6/src/names_data.jl

shouldn't be changed from `Int64` to `UInt8`

**Comment by timholy** [comment]
I'm less worried about the data type and more about the value; should we use 1.0 instead of 255? 

The current conversions (including reinterpreting as `N0f8`) are done algorithmically here: https://github.com/JuliaGraphics/Colors.jl/blob/33ce6c0c4c3e654021d713e99d0d62c119b68044/src/parse.jl#L108-L110.

**Comment by scls19fr** [comment]
Working with float can lead to numerical issues...

this kind of values should be stored in a structure which can store for example fractional values (1/3 for example)

My 2 cts

**Comment by timholy** [comment]
Just FYI that table is only for internal use anyway, I don't think there's anything about it that leaks out to the user. By reinterpreting as `N0f8` we're effectively storing all of them at ratios with denominator 255.

```julia
julia> colorant"indianred"
RGB{N0f8}(0.804,0.361,0.361)

julia> dump(colorant"indianred")
RGB{FixedPointNumbers.Normed{UInt8,8}}
  r: FixedPointNumbers.Normed{UInt8,8}
    i: UInt8 0xcd
  g: FixedPointNumbers.Normed{UInt8,8}
    i: UInt8 0x5c
  b: FixedPointNumbers.Normed{UInt8,8}
    i: UInt8 0x5c
```
