### ISSUE TITLE
Approx wavelength to RGB converter [Suggested addition]

### ISSUE THREAD

**Issue by ianshmean** [JuliaGraphics/Colors.jl#334]
The conversion of wavelength to color on a RGB plane is a complicated can of worms.. but I needed something crude, so converted the code below. Perhaps it's useful to add to this package?

```julia
using ColorTypes
function wavelength_to_rgb(wavelength;gamma=0.8)
    #=
    Based on code by Dan Bruton http://www.physics.sfasu.edu/astro/color/spectra.html
    discussed: https://stackoverflow.com/questions/1472514/convert-light-frequency-to-rgb
    python version: https://gist.github.com/friendly/67a7df339aa999e2bcfcfec88311abfc
    
    =#
    if (wavelength >= 380) && (wavelength <= 440)
        attenuation = 0.3 + 0.7 * (wavelength - 380) / (440 - 380)
        R = ((-(wavelength - 440) / (440 - 380)) * attenuation) ^ gamma
        G = 0.0
        B = (1.0 * attenuation) ^ gamma
    elseif (wavelength >= 440) && (wavelength <= 490)
        R = 0.0
        G = ((wavelength - 440) / (490 - 440)) ^ gamma
        B = 1.0
    elseif (wavelength >= 490) && (wavelength <= 510)
        R = 0.0
        G = 1.0
        B = (-(wavelength - 510) / (510 - 490)) ^ gamma
    elseif (wavelength >= 510) && (wavelength <= 580)
        R = ((wavelength - 510) / (580 - 510)) ^ gamma
        G = 1.0
        B = 0.0
    elseif (wavelength >= 580) && (wavelength <= 645)
        R = 1.0
        G = (-(wavelength - 645) / (645 - 580)) ^ gamma
        B = 0.0
    elseif (wavelength >= 645) && (wavelength <= 750)
        attenuation = 0.3 + 0.7 * (750 - wavelength) / (750 - 645)
        R = (1.0 * attenuation) ^ gamma
        G = 0.0
        B = 0.0
    else
        R = 0.0
        G = 0.0
        B = 0.0
    end
    return RGB(R,G,B)
end
```
```julia
using Colors
wavelength_to_rgb.(320:1:800)
```
<img width="691" alt="Screen Shot 2019-06-27 at 2 11 15 PM" src="https://user-images.githubusercontent.com/1694067/60289877-776bd880-98e5-11e9-99ed-4d85a2aade32.png">

**Comment by cormullion** [comment]
Cool! If you make a PR (😅) note that the release number in Project.toml is currently wrong (it says 0.9.4 but the release is currently 0.9.5).

**Comment by ianshmean** [comment]
Done! I thought it made sense in `utilities.jl` but happy to move it if it should be elsewhere

**Comment by JeffBezanson** [comment]
Shouldn't the CIE matching functions be used for this, or is that not necessary/worse somehow?

**Comment by m-lohmann** [comment]
> Shouldn't the CIE matching functions be used for this, or is that not necessary/worse somehow?

It’s even more complex. @ianshmean’s implementation just fakes it, and it doesn’t do it very well. I guess it does its job for certain uses, but to get it done properly you need to use CIE matching functions (preferrably the CIE1964 10° observer), and you need to map it to sRGB, which is the most commonly used device color space. And this is the real problem because sRGB is so much smaller than the full gamut that you need to choose a proper mapping operator for a perceptually uniform result, or a result that’s even remotely accurate.

A few years ago I rendered a proper sRGB spectrum which is perceptually uniform, by reducing the contrast, which basically mimics a spectrum in a lit room, to reduce the contrast.

Here’s the spectrum: correct [mapping of 380 to 830 nm spectrum to sRGB in 5 nm steps](https://upload.wikimedia.org/wikipedia/de/9/9c/Farbmetrisch_korrektes_Farbspektrum_im_sRGB-Farbraum.png) without gamut clipping.

The main problem is the fact that the faked spectrum doesn’t take into account the brightness perception that varies with the wavelength, and the fact that sRGB has big problems with cyan colors, which aren’t covered very well in its gamut.

There are ways to map spectral colors less accurately but visually more pleasing and still accurate enough, but @ianshmean’s version is just a quick hack.

**Comment by ianshmean** [comment]
> As long as everyone is aware that @ianshmean’s version is a quick hack, there’s nothing wrong with using it, of course.

I agree. I tried to make that clear in the docstring over in #335:
```
"""
    wavelength_to_rgb(wavelength;gamma=0.8)

An approximate conversion of optical wavelength (nm) to RGB.
Based on https://gist.github.com/friendly/67a7df339aa999e2bcfcfec88311abfc
Which is a conversion of code by Dan Bruton http://www.physics.sfasu.edu/astro/color/spectra.html
And discussed: https://stackoverflow.com/questions/1472514/convert-light-frequency-to-rgb
"""
```
but perhaps the function name should also include the word approximate?

Obviously if there's a better implementation, then we should strive for accuracy!

**Comment by cormullion** [comment]
I'd say merge this now if it's useful and leave a note that it can be improved by someone down the line... (Perhaps add a `FIXME` annotation like they do in base Julia. 😂)

**Comment by JeffBezanson** [comment]
Maybe there should be a more accurate function that returns a color in XYZ space, so the thorny problems are kicked to whoever wants RGB.

**Comment by KelSolaar** [comment]
> Maybe there should be a more accurate function that returns a color in XYZ space, so the thorny problems are kicked to whoever wants RGB.

Hi,

Yes! I would suggest doing that. You just need to get the values from the CMFS and interpolate if you are being requested values in-between the interval. This is way much cleaner than the above approximation which I would not recommend using.

Example: You need the CIE XYZ tristimulus values for the *CIE 1931 2 Degree Standard Observer* at 380nm you would just need to return directly those values: https://github.com/colour-science/colour/blob/41cef0e7336c8e565b5c7f7a1e4b599ea090861a/colour/colorimetry/datasets/cmfs.py#L1393

Cheers,

Thomas

**Comment by m-lohmann** [comment]
@KelSolaar: The CMFs, and even their current and several more modern variants published by the CIE are already part of the `Colors.jl` package, in the file `colormatch.jl`.

**Comment by ianshmean** [comment]
Oh, right.. this already works! 🤦‍♂️
```julia
using Colors
RGB.(colormatch.(320:800))
```
![image](https://user-images.githubusercontent.com/1694067/60389925-16850180-9a99-11e9-9a0c-3a0f74c94a4d.png)

**Comment by KelSolaar** [comment]
> @KelSolaar: The CMFs, and even their current and several more modern variants published by the CIE are already part of the `Colors.jl` package, in the file `colormatch.jl`.

Ha! Then you don't need the above PR! :D

**Comment by ianshmean** [comment]
I've converted https://github.com/JuliaGraphics/Colors.jl/pull/335 into a docs update, to highlight the above.

**Comment by cormullion** [comment]
I merged the doc update. I'm going to add some missing docstrings soon and head for a release after that.
