### ISSUE TITLE
Displaying `TransparentColor` as SVG

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#343]
`Color` and array of `Color` data can be displayed as SVG.
Is there a demand for displaying `TransparentColor`?

A `TransparentColor` (not arrays) can be displayed by the following function:
```julia
function Base.show(io::IO, mime::MIME"image/svg+xml", c::TransparentColor)
    id = "pat_" * string(rand(UInt32), base=62)
    hexc = hex(color(c))
    op = alpha(c)
    write_declaration(io, mime) # see  https://github.com/JuliaGraphics/Colors.jl/pull/342
    write(io,
        """
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1"
             width="25mm" height="25mm" viewBox="0 0 1 1" stroke="none">
             <defs>
                <pattern id="$id" width=".2" height=".2"
                         patternUnits="userSpaceOnUse">
                    <path d="M.1,0h.1v.1h-.2v.1h.1z" fill="#999" opacity=".5" />
                </pattern>
             </defs>
             <rect width="1" height="1" fill="url(#$id)" />
             <path d="M1,0v1h-1z" fill="#$hexc" />
             <rect width="1" height="1" fill="#$hexc" fill-opacity="$op" />
        </svg>
        """)
    flush(io)
end
```
![transparentcolor](https://user-images.githubusercontent.com/12679384/64062420-0c11f000-cc21-11e9-9112-128f09caa568.png)

Displaying SVG matrices of `TransparentColor` requires attention to performance issues, since `ImageShow.jl` suppresses [only the SVG matrices of `Color`](https://github.com/JuliaImages/ImageShow.jl/blob/d9843bce9d7a7d3aa51dd02862d9dee3a2407626/src/showmime.jl#L13-L17).

**Comment by kimikage** [comment]
The result of vector (1-D array) version looks like this:
![transparent_vector](https://user-images.githubusercontent.com/12679384/64063721-09b89180-cc33-11e9-89a9-fa24d901a968.jpg)

**Comment by timholy** [comment]
I like it!

**Comment by kimikage** [comment]
The latter design was implemented and merged.
