### ISSUE TITLE
Matplotlib defailt colors as named colors

### ISSUE THREAD

**Issue by ajwheeler** [JuliaGraphics/Colors.jl#347]
It would be neat if the matplotlib default colors were named colors in Colors.jl.  I recently make plot with StatsPlots.jl that I wanted to match several plots made with PyPlot, and it would have saved a couple minutes if I didn't have to look up and set them by hand.

**Comment by timholy** [comment]
Pull request? https://github.com/JuliaGraphics/Colors.jl/blob/master/src/names_data.jl has the current names.

**Comment by ajwheeler** [comment]
I'm happy to submit a pull request.  Do you have an opinion about what the colors should be called?  The most obvious thing is to give them the same names as in matpltlib: `C0`, `C1`, etc, but maybe that's a bit opaque?

**Comment by timholy** [comment]
Is there a reference for the names? How many are we talking?

**Comment by kimikage** [comment]
It is an important topic that the matplotlib's "CN" color spec is based on *rendering-time* evaluation.

https://matplotlib.org/api/colors_api.html
> a "CN" color spec, i.e. 'C' followed by a number, which is an index into the default property cycle (matplotlib.rcParams['axes.prop_cycle']); the indexing is intended to occur at rendering time, and defaults to black if the cycle does not include color.

If you just need the default 10 colors (aka tab10), they are found in [ColorSchemes](https://github.com/JuliaGraphics/ColorSchemes.jl).`tab10`.

I cannot completely agree to the proposeal to add the concrete colors named as "C0", "C1", ..., "C9".
