### ISSUE TITLE
[RFC]  Whether RGB <-> XYZ conversion should be more faster or be kept simple

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#351]
This is not an issue report. And, I have not decided a vision of what it should be.

I was interested in the following comment in another issue.
> But here it doesn't matter because most of the time is taken up by the `v^(1/2.4)` operation in `srgb_compand`.

_Originally posted by @timholy in https://github.com/JuliaGraphics/Colors.jl/issues/349#issuecomment-531460698_

And then, I gave it a try eliminating `^` with `Float32` precision. (I bet there's a better way.)

```julia
function srgb_compand(v::Float32)
    v <= 0.0031308f0 && return 12.92v
    x = sqrt(Float64(v))
    if v >= 0.25f0
        return  -0.027068702898623787 + x*(1.3721685639381944 + x*(
                -0.8182691289384268   + x*(1.0130285191962123 + x*(
                -0.9480751093798352   + x*(0.5864252237648636 + x*(
                -0.2120914317979767   + x*(0.03388206630456692)))))))
    elseif v >= 0.015625f0
        return  -0.04681200154477308  + x*(1.7595676106892333 + x*(
                -4.800335523711974    + x*(28.963281530269672 + x*(
                -144.84684738192738   + x*(551.4601017130509  + x*(
                -1559.1686261466277   + x*(3207.764496252879  + x*(
                -4656.012229629203    + x*(4512.997609562684  + x*(
                -2619.2703123846018   + x*(687.9857377729561)))))))))))
    else
        return  -0.050769586670801364 + x*(2.004280478094793  + x*(
                -11.749002783289283   + x*(146.84612431888658 + x*(
                -1443.135076339118    + x*(9983.922783293772  + x*(
                -45370.79700636592    + x*(121264.00163436493 + x*(
                -144305.83989718332))))))))
    end
end
```
Since the sRGB matrix transformation is (substantially) always done [in `Float64`](https://github.com/JuliaGraphics/Colors.jl/blob/e7f4723e3da81803e8dd392513d11917117d0d21/src/conversions.jl#L140-L147), I changed the type of the matrix elements to `Float32`. (Formally, it may be better to keep them in `Float64` for `XYZ{Float64}`.)

Then, it certainly worked as I expected.

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

julia> using BenchmarkTools

julia> @benchmark convert(RGB{Float64}, x) setup=(x=XYZ{Float64}(rand(),rand(),rand()))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     76.185 ns (0.00% GC)
  median time:      156.340 ns (0.00% GC)
  mean time:        168.913 ns (0.00% GC)
  maximum time:     1.117 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     970

julia> @benchmark convert(RGB{Float32}, x) setup=(x=XYZ{Float32}(rand(),rand(),rand()))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     13.427 ns (0.00% GC)
  median time:      19.438 ns (0.00% GC)
  mean time:        20.656 ns (0.00% GC)
  maximum time:     101.503 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     998

julia> @benchmark convert(RGB{Float64}, x) setup=(x=rand(Lab{Float64}))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     91.615 ns (0.00% GC)
  median time:      169.392 ns (0.00% GC)
  mean time:        177.020 ns (0.00% GC)
  maximum time:     446.016 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     954

julia> @benchmark convert(RGB{Float32}, x) setup=(x=rand(Lab{Float32}))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     36.995 ns (0.00% GC)
  median time:      46.673 ns (0.00% GC)
  mean time:        48.788 ns (0.00% GC)
  maximum time:     131.955 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     992
```

Since the RGB <-> XYZ conversion is used frequently, I think it is worth specializing. However, I also think that such an ad hoc function is not elegant.

Do you have any thoughts?

**Comment by johnnychen94** [comment]
Is [generated function](https://docs.julialang.org/en/v1/manual/metaprogramming/#Generated-functions-1) designed for this situation?

**Comment by kimikage** [comment]
Am I correct in understanding that generating the approximate expressions (e.g. polynomials) can be done in compile-time?
From my understanding, the *generated function* may be helpful for supporting various gamma values, but in the case of the constant gamma `2.4`, the meta implementation may be as complicated as a concrete implementation as shown above.

**Comment by timholy** [comment]
>  generating the approximate expressions (e.g. polynomials) can be done in compile-time?

I agree, I wouldn't do this with a generated function.

I really like the speedup. I might consider using a [continued fraction](https://en.wikipedia.org/wiki/Continued_fraction) representation instead. Some such representations are [here](http://functions.wolfram.com/ElementaryFunctions/Power/10/). Since `2.4 == 12//5` there may be even faster approaches.

I am not certain one has to get full mathematical precision, since our ability to discriminate colors has limits. But of course precision is convenient, especially for tests, so we shouldn't give it up too lightly.

> I'm disgusted by the dull test/conversion.jl, though.

Yeah, tests have long been a sore point. The JLD-based tests were an attempt to improve the situation, but more could be done.

**Comment by kimikage** [comment]
Interestingly, `exp(1/2.4 * log(x))` is faster than `x^(1/2.4)`. And curiously, it is also faster than `exp2(1/2.4 * log2(x))`.
This may change in future releases of Julia (or LLVM), but currently it looks like a useful (and maybe-not-so-ugly) hack.

```julia
julia> @benchmark x^(1/2.4) setup=(x=max(rand(),0.0031308))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     57.274 ns (0.00% GC)
  median time:      57.884 ns (0.00% GC)
  mean time:        60.855 ns (0.00% GC)
  maximum time:     77.416 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     983

julia> @benchmark exp(1/2.4 * log(x)) setup=(x=max(rand(),0.0031308))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     10.910 ns (0.00% GC)
  median time:      15.917 ns (0.00% GC)
  mean time:        18.759 ns (0.00% GC)
  maximum time:     38.437 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999

julia> @benchmark exp2(1/2.4 * log2(x)) setup=(x=max(rand(),0.0031308))
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     24.874 ns (0.00% GC)
  median time:      25.476 ns (0.00% GC)
  mean time:        25.388 ns (0.00% GC)
  maximum time:     47.442 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     997
```

**Comment by kimikage** [comment]
I merged the PR #352 since there is almost no loss in accuracy.
However, if we allow the loss, there are various techniques for speeding up. The polynomial approximation as shown above is even faster than the PR #352.

So, I would like to continue this discussion for a while.

**Comment by kimikage** [comment]
I know that `5/12 ≈ 1/2`, but I did not noticed at all that `5/12 == 1/2 + 1/4 - 1/3`.
In short, we can use this:
```julia
pow3_4(x) = (y=sqrt(x); y * sqrt(y))
pow5_12(x) = pow3_4(x) / cbrt(x)
```
`cbrt(x)` is not so fast, but `pow5_12(x)` is slightly faster than `exp(1/2.4 * log(x))`.

On the other hand, as `5` is a prime, I think this technique is not effective for `invert_srgb_compand()`.
`12/5 == 2 + 2/5 == 2 + 1/2 - 1/10` may help accelerating the rate of convergence, but I don't know what algorithm is the best. The best way may possibly be using MKL, though.

**Comment by kimikage** [comment]
## Benchmark (snip.)
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### before (43d93ffbe855b298fceda03cb2d730b1c223981d)
```julia
julia> @benchmark convert(RGB{Float64}, x) setup=(x=XYZ{Float64}(rand(),rand(),rand()))
  minimum time:     19.658 ns (0.00% GC)
  median time:      45.737 ns (0.00% GC)
  mean time:        50.024 ns (0.00% GC)
  maximum time:     176.429 ns (0.00% GC)

julia> @benchmark convert(RGB{Float32}, x) setup=(x=XYZ{Float32}(rand(),rand(),rand()))
  minimum time:     21.465 ns (0.00% GC)
  median time:      45.135 ns (0.00% GC)
  mean time:        48.481 ns (0.00% GC)
  maximum time:     147.642 ns (0.00% GC)

julia> @benchmark convert(XYZ{Float64}, x) setup=(x=RGB{Float64}(rand(),rand(),rand()))
  minimum time:     20.583 ns (0.00% GC)
  median time:      54.618 ns (0.00% GC)
  mean time:        55.775 ns (0.00% GC)
  maximum time:     143.372 ns (0.00% GC)

julia> @benchmark convert(XYZ{Float32}, x) setup=(x=RGB{Float32}(rand(),rand(),rand()))
  minimum time:     23.193 ns (0.00% GC)
  median time:      59.839 ns (0.00% GC)
  mean time:        61.497 ns (0.00% GC)
  maximum time:     153.012 ns (0.00% GC)
```
### after (https://github.com/kimikage/Colors.jl/commit/686019193545b58c790cf09428f36b4d2e821091)
```julia
julia> @benchmark convert(RGB{Float64}, x) setup=(x=XYZ{Float64}(rand(),rand(),rand()))
  minimum time:     19.357 ns (0.00% GC)
  median time:      30.792 ns (0.00% GC)
  mean time:        33.945 ns (0.00% GC)
  maximum time:     92.979 ns (0.00% GC)

julia> @benchmark convert(RGB{Float32}, x) setup=(x=XYZ{Float32}(rand(),rand(),rand()))
  minimum time:     20.762 ns (0.00% GC)
  median time:      31.293 ns (0.00% GC)
  mean time:        35.580 ns (0.00% GC)
  maximum time:     122.969 ns (0.00% GC)

julia> @benchmark convert(XYZ{Float64}, x) setup=(x=RGB{Float64}(rand(),rand(),rand()))
  minimum time:     19.559 ns (0.00% GC)
  median time:      54.162 ns (0.00% GC)
  mean time:        56.013 ns (0.00% GC)
  maximum time:     131.896 ns (0.00% GC)

julia> @benchmark convert(XYZ{Float32}, x) setup=(x=RGB{Float32}(rand(),rand(),rand()))
  minimum time:     13.213 ns (0.00% GC)
  median time:      20.521 ns (0.00% GC)
  mean time:        21.990 ns (0.00% GC)
  maximum time:     89.189 ns (0.00% GC)
```

**Comment by kimikage** [comment]
Umm...:confused:
I hope the (implicit) SIMD optimization will be a little smarter.
```julia
function invert_srgb_compand(v::Float32)
    i = unsafe_trunc(Int32, v * 255)
    (i < 13 || i > 255) && return invert_srgb_compand(Float64(v))
    @inbounds y = view(invert_srgb_compand_n0f8, i:i+3)
    dv = v * 255.0 - i
    dv == 0.0 && @inbounds return y[2]
    if v < 0.38857287f0
        return @fastmath(y[2]+0.5*dv*((-2/3*y[1]- y[2])+(2y[3]-1/3*y[4])+
                                  dv*((     y[1]-2y[2])+  y[3]-
                                  dv*(( 1/3*y[1]- y[2])+( y[3]-1/3*y[4]) ))))
    else
        return @fastmath(y[2]+0.5*dv*((4y[3]-3y[2])-y[4]+dv*((y[4]-y[3])+(y[2]-y[3]))))
    end
end
```

**Comment by johnnychen94** [comment]
Will this PR be influenced by https://github.com/JuliaMath/FixedPointNumbers.jl/issues/125 ?

**Comment by kimikage** [comment]
The answer is probably no, because the RGB <--> XYZ conversions mainly use `Floats`, not `FixedPointNumbers`. Of course, if `FixedPointNumbers` such as `Q7f24` will have much greater performance than `Float32`, using them will be yet another strategy to improve the conversions.

**Comment by kimikage** [comment]
I learned a little about Julia's inlining. cf. https://github.com/JuliaMath/FixedPointNumbers.jl/issues/129#issuecomment-548888619
FYI, *usually*, inlining `pow12_5` is effective for the caller (`invert_srgb_compand(v::Fractional)`), but it may have the opposite effect for the caller's caller (`invert_srgb_compand(v::Float32)`).
https://github.com/kimikage/Colors.jl/commit/f78900003a2c0acec9b216468e725f9dd3d7356a
```julia
# `pow12_5` is called from `invert_srgb_compand`.
# x^y ≈ exp(y*log(x)) ≈ exp2(y*log2(y)); the middle form is faster
@noinline pow12_5(x) = x^2 * exp(0.4 * log(x)) # 12/5 == 2.4 == 2 + 0.4
```

**Comment by kimikage** [comment]
I'm going to change the significant digits of numbers in the sRGB matrices from ∼7 to ∼16. (cf. https://github.com/JuliaGraphics/Colors.jl/issues/355#issuecomment-539524932) Paradoxically, this provides a backing that the accuracy can be lowered with lower precision types than `Float64`.
Strictly speaking, this will be a breaking change (cf. #361), but I think it is negligible because the current numbers also do not follow the sRGB specification.

Is there a problem?

**Comment by timholy** [comment]
Sounds good to me. Once we've made one breaking change (and recent changes in FixedPointNumbers probably qualify, I have a PR I should submit for ColorVectorSpace that fixes one of the tests), there's little reason to hold back. Might as well get things "right."

**Comment by kimikage** [comment]
BTW, even if there is not enough color gamut support, the conversion matrices can be obtained dynamically (in the precompilation) when the color primaries are defined. (cf. https://github.com/JuliaGraphics/Colors.jl/issues/372#issuecomment-562949564)
Although some errors occur in the calculation of the inverse matrix, there is no problem perceptually.
