### ISSUE TITLE
[RFC] Order of alpha in hex notation of TransparentColor (#AARRGGBB or #RRGGBBAA)

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#353]
I was just wondering...
In Colors.jl v0.5.0-v0.9.6, `hex(::TransparentColor)` returns the hex notation in the "AARRGGBB" style. 
https://github.com/JuliaGraphics/Colors.jl/blob/be3e641d2193df646f1696cdce3d33d8dc62c7ee/src/utilities.jl#L24-L33
(`TransparentColor` means {x | x∊ `Colorant` ∧ x∉`Color`}.)

As it is a simple representation of `ARGB32`, the "AARRGGBB" is commonly used (e.g. in Android SDK).
However, there is another common style "RRGGBBAA", too. The [CSS Color Module Level 4 (Editor's Draft)](https://drafts.csswg.org/css-color-4/#hex-notation) introduced this style, and multiple browsers have already [supported it](https://caniuse.com/#feat=mdn-css_properties_color_alpha_hexadecimal_notation).

So, what about splitting `hex(::TransparentColor)` into two, i.e. `hex(::AlphaColor)` returning "AARRGGBB" and `hex(::ColorAlpha)` returning "RRGGBBAA"?

However, this is a breaking change and may affect to the color parsing.
The current Colors.jl does not support parsing the 8-digit or 4-digit hex notation.
```julia
julia> hex(colorant"#FF8000demo") # this is parsed as a opaque orange `RGB{N0f8}` without errors.
"FF8000"

julia> hex(colorant"0xFF8000demo") # same as above
"FF8000"

julia> colorant"reddwarf" # this is not parsed as "red", though.
ERROR: LoadError: Unknown color: reddwarf
```
(I think there are some *minor* problems with the color parser. I'll report a new issue and send a PR.)

Since the "#RRGGBB" notation comes from the CSS Level 3, I think "#FF8000DE" should be parsed as a transparent orange (`RGBA{N0f8}`) according to the CSS manner.
On the other hand, since the "0xRRGGBB"  notation comes from the binary representation, I think "0xFF8000DE" should be parsed as a opaque purple (`ARGB{N0f8}`).
Although this may cause confusion and need the docs, the correspondence between `hex()` and `parse()` is clear.

FYI, "rgba()", "hsla()" and "transparent" are parsed into `RGBA{N0f8}` (not `ARGB{N0f8}`). So, this is compatible with my plan.
```julia
julia> colorant"rgba(255,128,0,0.87)", colorant"transparent"
(RGBA{N0f8}(1.0,0.502,0.0,0.871), RGBA{N0f8}(0.0,0.0,0.0,0.0))
```

**Comment by timholy** [comment]
What about making it
```julia
@deprecate hex(c) hex(AlphaColor, c)
hex(::Type{AlphaColor}, c) = ...
hex(::Type{ColorAlpha}, c) = ...
```
(I'm not sure we should deprecate the 1-arg version, but worth discussing.)

**Comment by kimikage** [comment]
In point of neutrality, I think it is better.
However, the name of `hex()` is a vestige of Julia v0.x (where `hex(123)` returns `"7b"`), you know.
And I bet that quite a few user scripts define `hex(x) = string(x, base = 16)`. :ghost:
So, I think the shortness and simplicity are important, and it's better not to deprecate the 1-arg version. If we prioritize strictness over simplicity, the name `hex` should be changed.

**Comment by kimikage** [comment]
As interim measures, it may be a possible option to add `hex(::Type{ColorAlpha}, c) = (@warn("the position of alpha is going to be changed in the future release.") ...)`.
I don't think it is really useful, though.

I think it is better to add `hex (c :: RGBA)` and the support for parsing "#RRGGBBAA" in the same release. Then we may add `hex (c :: ColorAlpha)` later.

**Comment by kimikage** [comment]
By the way, using `RGB24` is faster, although I like `lerp()`.
```julia
function hex_(c::RGB24)
    u32 = reinterpret(UInt32, c)
    String([b"0123456789ABCDEF"[u32 << i >>> 28 + 1] for i = 8:4:28])
end
hex_(c::Color) = hex_(convert(RGB24, c))
```

```julia
julia> hex_(colorant"#C0FFEE")
"C0FFEE"

julia> @btime hex(c) setup=(c=rand(RGB));
  118.934 ns (4 allocations: 256 bytes)

julia> @btime hex_(c) setup=(c=rand(RGB));
  52.496 ns (2 allocations: 128 bytes)

julia> @btime hex(c) setup=(c=rand(Lab));
  147.488 ns (4 allocations: 256 bytes)

julia> @btime hex_(c) setup=(c=rand(Lab));
  77.741 ns (2 allocations: 128 bytes)
```
I'm not worried, but `uppercase ()` / `lowercase ()` was slower than my expectation, because they target not ASCII but UTF-8.

**Comment by kimikage** [comment]
I’d like to add something about `hex(::Type{AlphaColor}, c)`/`hex(::Type{ColorAlpha}, c)`. These methods may be called by something like `hex(LabA, c)`, although it returns ”RRGGBBAA”. So, I think `hex(::Type{ARGB}, c)`/`hex(::Type{RGBA}, c)` is better.
If we keep the 1-arg version, only users who currently use `hex(c::ColorAlpha)` to get "AARRGGBB" will rewrite `hex(c)` to `hex(ARGB, c)`. However, ColorTypes.jl provides [`ARGB32(c)`](https://github.com/JuliaGraphics/ColorTypes.jl/blob/7ef745605d6a0897078712a0a7a156c51295b559/src/conversions.jl#L57-L62), so we can use `hex(ARGB32(c))` instead of `hex(ARGB, c)`. Therefore, the issue in this case is how to tell the users about the breaking change.

**Comment by kimikage** [comment]
## Candidates
Please add plans or comments.

- Introduce Braking Changes
  - Break (Remove) `hex(::TransparentColor)`
    - Add `hex(::ColorAlpha)` and `hex(::AlphaColor)`
    - Add `hex(::RGBA)` without implicit conversion
- Keep Backward Compatibility
  - Add `hex(::Type{C}, c)`
    - where `C <: AlphaColor` or `C <: ColorAlpha`
    - where `C <: ARGB` or `C <: RGBA`
    - where `C` in all color types (e.g. `LabA`)
  - Add newly-named function (e.g. `hex_argb`, `hex_rgba`)
  - Add new function for generating CSS `<color>` type string (e.g. `css_string(c::Colorant; kwargs...)`)
  - Enhance `Base.string`

**Comment by timholy** [comment]
What about providing `hex(RGBA, c)` and `hex(ARGB, c)` to control the output no matter what type `c` has, `hex(c::ColorAlpha)` and `hex(c::AlphaColor)` defaulting to `hex(RGBA, c)` and `hex(ARGB, c)` respectively?

**Comment by kimikage** [comment]
> What about providing hex(RGBA, c) and hex(ARGB, c) to control the output no matter what type c has, hex(c::ColorAlpha) and hex(c::AlphaColor) defaulting to hex(RGBA, c) and hex(ARGB, c) respectively?

I think it is one of good plans, so I added it to the list (tree?).

Here is the summary of my comments above which are difficult to understand.
- The only styles we can provide *immediately* are "RRGGBB", "AARRGGBB" and "RRGGBBAA".
    - There are other "hex" notations potentially, e.g.:
       - 3-digit or 4-digit notations: "RGB", "ARGB", "RGBA"
       - non-RGB colorspace notations: "HHSSVV", "YYUUVV", "LLaabb", ...
- The former two styles (i.e. "RRGGBB" and "AARRGGBB") are already supported.
- The last "RRGGBBAA" style might be supported by *additional* `hex(c::ColorAlpha)`
- We can get the *current* "AARRGGBB" style of a `ColorAlpha`, by means of *current* `hex(ARGB32(c))` or `hex(c |> ARGB32)`

There seems to be a potential and essential problem with "hex(::Type{C}, c)" because the colortypes (excepting "RGB24", "ARGB32", "Gray24" and "AGray32") and the hex notations do not correspond *strictly*.

So, I added another plan, "Add optional argument (e.g. hex(c, style=:rrggbb))". The `style` may be something like `:aarrggbb`, `:rrggbb`, `:rgb`, `:shortest` and so on. However, this plan may have a problem on the speed performance.

**Comment by timholy** [comment]
We don't have to support `hex(::Type{C}, c)` for arbitrary `C`. It's fine to just define methods for specific type arguments, e.g., `hex(::Type{ARGB}, c)`. We wouldn't even support `hex(ARGB{N0f8}, c)`, for example, because there is no sense in which the numeric precision is supportable.

But the keyword argument would also be fine. If the generation involves printing I suspect that this would not be the bottleneck for performance.

**Comment by kimikage** [comment]
> We don't have to support `hex(::Type{C}, c)` for arbitrary `C`.

I agree with you. What I want to say is that the first argument has very limited functionality, i.e. selecting "AARRGGBB" or "RRGGBBAA". Of course, it is not a fatal problem.

**Comment by timholy** [comment]
Agreed. Sounds like benchmarking will solve this. If the keyword is just as fast, it seems likely to be better.

**Comment by kimikage** [comment]
Well, I tend to introduce [this kind of cheat](https://github.com/JuliaGraphics/Colors.jl/issues/353#issuecomment-533857683) for benchmarking, so I would like to ask more people for their opinion. :stuck_out_tongue_closed_eyes:

**Comment by kimikage** [comment]
> I don't think it is good idea to add "types" for hex notations.

Perhaps adding a *private* types is not so bad.
If you want to use the multiple dispatch instead of long `if`-`else` statements, you can use `Val{:symbol}`, but the cost of `Val(:symbol)` is expensive. So, the lookup table might be helpful. However, if you use a lookup table, you don't need to use `Val`. (Well, I personally don't like `@enum`.)

**Comment by kimikage** [comment]
Since it is going to take a little longer, I post the link of diff: https://github.com/JuliaGraphics/Colors.jl/compare/master...kimikage:hex_style

First of all, I would like to clarify the following points:
- backward compatibility
  - cf. `_hex(::Type{HexAuto}, c::ColorAlpha)`
- use of `Symbol`

I'm worried about the slowdown (and I think we can improve it). However, it is not fatal, so we can choose to postpone the performance improvement.

The 3-digit and 4-digit notation have a minor problem with rounding. They cause rounding errors twice.

Perhaps, some users hope to add a preamble (ie "#" or "0x"). Although it is technically not difficult, it may require meta-programming, or macros.

**Comment by kimikage** [comment]
BTW, `Base.hex` is no longer a public API, so don't forget to change it to `Colors.hex`.
https://github.com/JuliaGraphics/Colors.jl/blob/8e2c7dc0659ab7a6699eb5d90b99fda6ea29aff0/src/Colors.jl#L14

**Comment by timholy** [comment]
I'm a big fan of `hex(c, style=:rrggbb))`. As you say, there is a big advantage in not using types for this because compile latency is often more of a problem than runtime performance, and a simple runtime check is often not very expensive.

**Comment by kimikage** [comment]
In fact, my current implementation uses *private* types (e.g. `HexNotation`) internally, because I didn't want to write long `if`-`else` statements, rather than for the speed.
I think the biggest advantage of using symbols is the information hiding. We can improve the performance or add new styles without impacts to the user scripts. It's not nice to say this, but we can leave the responsibility for  problems to someone in the future. :smile:

**Comment by kimikage** [comment]
PR #387 was merged.
The transition measure will end when Colors v1.0 is released.
