### ISSUE TITLE
Inconsistency in handling hues

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#379]
Unnormalized hues are somewhat useful in the interpolation. In other words, the interpolation across 0° is not possible with only the normalized hues.

However, the manners of input range checking in conversions vary (cf. #378 ), and some conversions cannot handle unnormalized hues correctly.

```julia
using Colors

range(HSV(0,1,1), HSV(360,1,1),length=120)
range(HSV(0,1,1), HSV(-360,1,1),length=120)
range(HSV(0,1,1), HSV(720,1,1),length=120)
range(HSL(0,1,0.5), HSL(720,1,0.5),length=120)
range(HSI(0,1,1/3), HSI(720,1,1/3),length=120)
range(LCHab(70,70,0), LCHab(70,70,720),length=120)
range(LCHuv(70,70,0), LCHuv(70,70,720),length=120)
```

![hue](https://user-images.githubusercontent.com/12679384/70864262-cee52a00-1f93-11ea-893c-74245108a69b.png)

I think that the strictness of input range checking should be more consistent. Apart from that, it might be a good idea to add some utility functions related to the hue, such as `normalize_hue(c)`.

**Comment by kimikage** [comment]
Just out of my curiosity, @johnnychen94,what are your concerns? Use of unnormalized hues? Backward compatibility? Additional costs for the normalizing?

**Comment by johnnychen94** [comment]
Hmmm, I'm not familiar with this topic, but as far as I can think of, normalizing a channel needs `maxvalue` of that channel, do we have some kind of assumption/defaults on it? For Grays and RGBs we can infer the max value from the storage type (e.g., `N0f8` => 255), but since hue is stored as floats, we generally don't have such information, right? If you need to manually pass a `maxvalue` to `normalize_hue`, it might be a just not so convenient util.

**Comment by kimikage** [comment]
I see. Because of the problems which you point out, I focused only on the hue, which should be simply normalized to [0, 360], not to [0, 1].

BTW, I think the color gamut problem must be solved somewhere (cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/140). It is probably too early to put the gamut support in Colors.jl v1.0.

**Comment by johnnychen94** [comment]
I'm thinking of such kind of normalization:

```julia
function normalize_hue(x::T; maxvalue, minvalue) where T<:HSV
h_max= gamutmax(T)[1]
HSV(h_max*(x.h-minvalue)/(maxvalue-minvalue), x.s, x.v)
end

julia> normalize_hue(HSV(-360, 1, 1); maxvalue=360, minvalue=-360)
HSV{Float32}(0.0f0,1.0f0,1.0f0)

```

**Comment by kimikage** [comment]
Although I don't think the idea is bad, I can't imagine the practical use cases. At least, the behaviors with the hues which are not normalized to [0,360] are currently undefined (not documented).
"Apart from that" means that.

**Comment by timholy** [comment]
When a particular field represents an angle in degrees, generally we should interpret that number modulo 360. It's probably just that no one really needed this systematically before, or not enough to submit a PR, or we lacked tests to catch changes which broke this behavior. It would be fine to fix this.

**Comment by kimikage** [comment]
I will modifiy the conversion codes for `HSV`, `HSL` and `HSI`.
BTW, is this expected behavior?
```julia
julia> HSV(colorant"red")
HSV{Float32}(360.0f0,1.0f0,1.0f0)
```
Of course, this is definitely red, but this gives strange results in the interpolation.
![hsv](https://user-images.githubusercontent.com/12679384/75137633-749edd00-572b-11ea-9fa1-87d41a48d194.png)

**Comment by kimikage** [comment]
# Benchmark (TBC)
## Script
```julia
using BenchmarkTools
using FixedPointNumbers
using Colors

rgb_n0f8 = rand(RGB{N0f8},64,64);
rgb_f32  = rand(RGB{Float32},64,64);
rgb_f64  = rand(RGB{Float64},64,64);
argb_n0f8 = rand(ARGB{N0f8},64,64);
argb_f32  = rand(ARGB{Float32},64,64);
argb_f64  = rand(ARGB{Float64},64,64);

rgbs = (rgb_n0f8, rgb_f32, rgb_f64, argb_n0f8, argb_f32, argb_f64);

for C in (HSV, HSL, HSI)
    AC = alphacolor(C)
    
    for T in (Float32, Float64)
        for mat in rgbs
            XC = eltype(mat) <: Color ? C{T} : AC{T}
            println(eltype(mat), "-> $XC")
            @btime convert.($XC, view($mat,:,:))
        end
        for mat in rgbs
            XC = eltype(mat) <: Color ? C{T} : AC{T}
            println(eltype(mat), "<- $XC")
            h = convert.(XC, mat)
            r = convert.(eltype(mat),h)
            all(t->isapprox(t...),zip(r, mat)) || @warn("failed") # verification
            @btime convert.($XC, view($h,:,:))
        end
    end
end
```

## Julia v1.3.1 x86_64-w64-mingw32
```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
### RGB --> HSV
|w64|`(A)HSV`<br>`{Float32}`<br>v0.11.2|`(A)HSV`<br>`{Float32}`<br>optimized||`(A)HSV`<br>`{Float64}`<br>v0.11.2|`(A)HSV`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

###  HSV --> RGB
|w64|`(A)HSV`<br>`{Float32}`<br>v0.11.2|`(A)HSV`<br>`{Float32}`<br>optimized||`(A)HSV`<br>`{Float64}`<br>v0.11.2|`(A)HSV`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

### RGB --> HSL
|w64|`(A)HSL`<br>`{Float32}`<br>v0.11.2|`(A)HSL`<br>`{Float32}`<br>optimized||`(A)HSL`<br>`{Float64}`<br>v0.11.2|`(A)HSL`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

###  HSL --> RGB
|w64|`(A)HSL`<br>`{Float32}`<br>v0.11.2|`(A)HSL`<br>`{Float32}`<br>optimized||`(A)HSL`<br>`{Float64}`<br>v0.11.2|`(A)HSL`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

### RGB --> HSI
|w64|`(A)HSI`<br>`{Float32}`<br>v0.11.2|`(A)HSI`<br>`{Float32}`<br>optimized||`(A)HSI`<br>`{Float64}`<br>v0.11.2|`(A)HSI`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

###  HSI --> RGB
|w64|`(A)HSI`<br>`{Float32}`<br>v0.11.2|`(A)HSI`<br>`{Float32}`<br>optimized||`(A)HSI`<br>`{Float64}`<br>v0.11.2|`(A)HSI`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |         | |         |         |
|`RGB{Float32}` |         |         | |         |         |
|`RGB{Float64}` |         |         | |         |         |
|`ARGB{N0f8}`   |         |         | |         |         |
|`ARGB{Float32}`|         |         | |         |         |
|`ARGB{Float64}`|         |         | |         |         |

**Comment by kimikage** [comment]
Note that `range` returns normalized hue now. (cf. PR #405)
![hue](https://user-images.githubusercontent.com/12679384/75549138-4ba38280-5a72-11ea-904b-4aa444e578c9.png)

**Comment by kimikage** [comment]
# Benchmark 2
## Julia v1.0.5 x86_64-pc-linux-gnu (Debian on *WSL*)
```julia
julia> versioninfo()
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```
### RGB --> HSV (unit: μs)
|linux|`(A)HSV`<br>`{Float32}`<br>v0.11.2|`(A)HSV`<br>`{Float32}`<br>optimized||`(A)HSV`<br>`{Float64}`<br>v0.11.2|`(A)HSV`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |  46.600 | |         |  52.500 |
|`RGB{Float32}` |         |  38.900 | |         |  42.500 |
|`RGB{Float64}` |         |  40.200 | |         |  39.000 |
|`ARGB{N0f8}`   |         |  56.000 | |         |  69.200 |
|`ARGB{Float32}`|         |  38.500 | |         |  42.800 |
|`ARGB{Float64}`|         |  43.000 | |         |  39.500 |

###  HSV --> RGB (unit: μs)
|linux|`(A)HSV`<br>`{Float32}`<br>v0.11.2|`(A)HSV`<br>`{Float32}`<br>optimized||`(A)HSV`<br>`{Float64}`<br>v0.11.2|`(A)HSV`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |  47.500 | |         |  48.800 |
|`RGB{Float32}` |         |  10.200 | |         |  47.400 |
|`RGB{Float64}` |         |  50.200 | |         |  29.200 |
|`ARGB{N0f8}`   |         |  73.600 | |         |  74.000 |
|`ARGB{Float32}`|         |  21.500 | |         |  48.900 |
|`ARGB{Float64}`|         |  51.500 | |         |  30.300 |

### RGB --> HSL (unit: μs)
|linux|`(A)HSL`<br>`{Float32}`<br>v0.11.2|`(A)HSL`<br>`{Float32}`<br>optimized||`(A)HSL`<br>`{Float64}`<br>v0.11.2|`(A)HSL`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |  48.500 | |         |  58.500 |
|`RGB{Float32}` |         |  42.000 | |         |  43.400 |
|`RGB{Float64}` |         |  41.700 | |         |  40.100 |
|`ARGB{N0f8}`   |         |  58.300 | |         |  70.700 |
|`ARGB{Float32}`|         |  41.600 | |         |  43.800 |
|`ARGB{Float64}`|         |  43.900 | |         |  40.800 |

###  HSL --> RGB (unit: μs)
|linux|`(A)HSL`<br>`{Float32}`<br>v0.11.2|`(A)HSL`<br>`{Float32}`<br>optimized||`(A)HSL`<br>`{Float64}`<br>v0.11.2|`(A)HSL`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         |  48.700 | |         |  50.000 |
|`RGB{Float32}` |         |  41.300 | |         |  45.600 |
|`RGB{Float64}` |         |  50.800 | |         |  45.200 |
|`ARGB{N0f8}`   |         |  73.300 | |         |  73.000 |
|`ARGB{Float32}`|         |  42.300 | |         |  48.400 |
|`ARGB{Float64}`|         |  51.900 | |         |  45.300 |

### RGB --> HSI (unit: μs)
|linux|`(A)HSI`<br>`{Float32}`<br>v0.11.2|`(A)HSI`<br>`{Float32}`<br>optimized||`(A)HSI`<br>`{Float64}`<br>v0.11.2|`(A)HSI`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         | 119.400 | |         | 176.200 |
|`RGB{Float32}` |         | 152.100 | |         | 177.100 |
|`RGB{Float64}` |         | 177.600 | |         | 175.400 |
|`ARGB{N0f8}`   |         | 135.400 | |         | 163.300 |
|`ARGB{Float32}`|         |  84.200 | |         | 109.700 |
|`ARGB{Float64}`|         | 105.900 | |         | 100.800 |

`HSI{Float64}` is slower because its intermediate variables have been changed to `Float64` from `Float32`(`floattype`).

###  HSI --> RGB (unit: μs)
|linux|`(A)HSI`<br>`{Float32}`<br>v0.11.2|`(A)HSI`<br>`{Float32}`<br>optimized||`(A)HSI`<br>`{Float64}`<br>v0.11.2|`(A)HSI`<br>`{Float64}`<br>optimized|
|:--------------|--------:|--------:|-|--------:|--------:|
|`RGB{N0f8}`    |         | 112.600 | |         | 117.500 |
|`RGB{Float32}` |         | 108.900 | |         | 119.000 |
|`RGB{Float64}` |         | 119.200 | |         | 113.500 |
|`ARGB{N0f8}`   |         | 154.600 | |         | 161.900 |
|`ARGB{Float32}`|         | 108.800 | |         | 120.200 |
|`ARGB{Float64}`|         | 119.700 | |         | 114.700 |

**Comment by kimikage** [comment]
BTW, I was going to send a PR for an improved version of #351 after a consensus was reached on the gamut or `rand` issues. However, the consensus building is likely to take some time. First, I have to start by attracting the developers and users.
I would like to submit an improved version of #351 with static conversion matrices instead of ones calculated dynamically from the color primaries.

**Comment by kimikage** [comment]
FYI, unfortunately, Julia nightly build can optimize the following `muladd` to a simple multiplication :sob::
```julia
div60(x::T) where T <: Union{Float32, Float64} = muladd(x, T(1/960), x * T(0x1p-6))
```
IMO, such an optimization is too drastic, but some people want it, so it is not a bug.
I have used `fma` instead of `muladd` here, but the same problem may occur in FixedPointNumbers.

**Comment by kimikage** [comment]
Quiz: Do you know what is different? :smile:
```julia
function _hsx_to_rgb(im::UInt8, v::T, n::T, m::T) where T <:Union{Float16, Float32, Float64}
    vu, nu, mu = reinterpret.(Unsigned, (v, n, m)) # prompt the compiler to use conditional moves
    r = ifelse((im & 0b100001) != 0x0, vu, ifelse((im & 0b010010) != 0x0, nu, mu))
    g = ifelse((im & 0b000110) != 0x0, vu, ifelse((im & 0b001001) != 0x0, nu, mu))
    b = ifelse((im & 0b011000) != 0x0, vu, ifelse((im & 0b100100) != 0x0, nu, mu))
    return reinterpret.(T, (r, g, b))
end
```
```julia
function _hsx_to_rgb(im::UInt8, v::T, n::T, m::T) where T <:Union{Float16, Float32, Float64}
    vu, nu, mu = reinterpret.(Unsigned, (v, n, m)) # prompt the compiler to use conditional moves
    r = ifelse((im & 0b100001) == 0x0, ifelse((im & 0b010010) == 0x0, mu, nu), vu)
    g = ifelse((im & 0b000110) == 0x0, ifelse((im & 0b001001) == 0x0, mu, nu), vu)
    b = ifelse((im & 0b011000) == 0x0, ifelse((im & 0b100100) == 0x0, mu, nu), vu)
    return reinterpret.(T, (r, g, b))
end
```

**Comment by johnnychen94** [comment]
> Quiz: Do you know what is different? 😄

Both are black magic spell to me :confused:

**Comment by kimikage** [comment]
I think this is "visually" easy to understand, so not so black. :smile:
```julia
if     hue <  60; im = 0b000001 # ---------+
elseif hue < 120; im = 0b000010 # --------+|
elseif hue < 180; im = 0b000100 # -------+||
elseif hue < 240; im = 0b001000 # ------+|||
elseif hue < 300; im = 0b010000 # -----+||||
else            ; im = 0b100000 # ----+|||||
end                             #     ||||||
(hue < 60 || hue >= 300) === ((im & 0b100001) != 0x0)
```

**Comment by kimikage** [comment]
In short, the root of the speed problem is the inlining. As pointed out earlier in FixedPointNumbers, there is no advantage to appending `@ inline` to `cnvt()`. The caller of `cnvt()` (i.e. `ColorTypes._convert()`) fails inlining. We should not add `@inline` to `ColorTypes._convert()`. Inlining the methods which do not benefit from inlining has a fatal performance penalty.

**Comment by kimikage** [comment]
> I have used `fma` instead of `muladd` here, but the same problem may occur in FixedPointNumbers.

> \# Disable LLVM's fma if it is incorrect, e.g. because LLVM falls back
> \# onto a broken system libm; if so, use openlibm's fma instead

https://github.com/JuliaLang/julia/blob/4d8f889464d5d9168e111d698b1c74a71ff24614/base/floatfuncs.jl#L321-L335

:scream:

**Comment by johnnychen94** [comment]
Hmmm, perhaps the color processing world doesn't need that kind of accuracy?

**Comment by timholy** [comment]
> after a consensus was reached on the gamut or `rand` issues.

If the main discussion is somewhere besides https://github.com/JuliaGraphics/ColorTypes.jl/issues/150, can you provide a link?

**Comment by kimikage** [comment]
cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/150#issuecomment-593130365

**Comment by kimikage** [comment]
> I will also look for workarounds other than `fma`.

_Originally posted by @kimikage in https://github.com/JuliaGraphics/Colors.jl/pull/407_

```julia
julia> versioninfo()
Julia Version 1.5.0-DEV.376
Commit ea067fb221 (2020-03-01 09:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> div60(x::Float64) = fma(x, 1/960, x * 0x1p-6); # What I just want is, 1 `vmul` and 1 `vfmadd`

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vmulsd  xmm1, xmm0, qword ptr [rax]
        movabs  rax, 761602336
        vfmadd132sd     xmm0, xmm1, qword ptr [rax]
...snip...

julia> div60(x::Float64) = muladd(x, 1/960, x * 0x1p-6); # but I don't want to use `fma()`, so, let's use `muladd()`

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vmulsd  xmm0, xmm0, qword ptr [rax] # Do you know the intent that I used the distributive law?
...snip...

julia> div60(x::Float64) = x * (1/960) + x * 0x1p-6; # OK, keep it simple stupid

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vmulsd  xmm1, xmm0, qword ptr [rax]
        movabs  rax, 761602592
        vmulsd  xmm0, xmm0, qword ptr [rax]
        vaddsd  xmm0, xmm1, xmm0            # Good! But you can get rid of this `add` by `fma`!
...snip...
        
julia> div60(x::Float64) = muladd(x, 1/960, muladd(x, 0x1p-6, 0.0)); # OK, OK. You can optimize `muladd` into `mul`.

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vxorpd  xmm1, xmm1, xmm1
        vfmadd231sd     xmm1, xmm0, qword ptr [rax] # Nice double `vfmadd`s!
        movabs  rax, 761601960
        vfmadd132sd     xmm0, xmm1, qword ptr [rax]
...snip...

julia> div60(x::Float64) = muladd(x, 1/960, muladd(x, 0x1p-7, x * 0x1p-7)); # You know the distributive law, right?

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vmulsd  xmm1, xmm0, qword ptr [rax]  # 1 `vmul` is OK,
        vaddsd  xmm1, xmm1, xmm1             # but did you forget the distributive law?
        movabs  rax, 761602088
        vfmadd132sd     xmm0, xmm1, qword ptr [rax]
...snip...

julia> div60(x::Float64) = muladd(x, 1/960, muladd(x, -0x1p-7, x * 0x3p-7)); # I apologize for the same 0x1p-7 confusing you.
div60 (generic function with 1 method)

julia> @code_native syntax=:intel div60(1.0)
...snip...
        movabs  rax, offset .rodata.cst8
        vmulsd  xmm0, xmm0, qword ptr [rax] # You know the distributive law! 
                                            # But you should learn that floating-point arithmetic does not have full associativity!
...snip...
```
:anger::anger::anger:

**Comment by kimikage** [comment]
Solved(?) by https://github.com/JuliaGraphics/Colors.jl/pull/407#discussion_r387472215

Please report when you get wrong colors or significant slowdowns.
