### ISSUE TITLE
Please revert the last commit!

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Colors.jl#394]
I don't know why the last commit was applied to master directly, I thought it was pushing to my fork. So you should probably revert

https://github.com/JuliaGraphics/Colors.jl/commit/318515cea4a24c3c2a330bc3b3ad33dec6d24897

I can't do it at the moment...

**Comment by timholy** [comment]
Oh dear, that's a very large pollution of the git history. I'm going to actually force-push rather than revert.

**Comment by cormullion** [comment]
Thanks Tim. No idea what happened here... :(

**Comment by kimikage** [comment]
I don't want to rub salt in the wound..., but what's happend?
The master until yesterday was 0890b410940fa9645496a394e5c449ef7104769a

**Comment by johnnychen94** [comment]
LOL I'm afraid Tim messed it up, you could rebase e8dc970d7f2d7fb93325526b1adbad5f6ec5038e on your branch (if you happened to have one)

**Comment by cormullion** [comment]
I was adding favicon.ico and then when I wanted to edit the latest docs/make.jl file I ended up pushing everything directly. I only know a few git commands and it’s very easy to get into trouble. 

Sorry!

**Comment by kimikage** [comment]
Since I have no experience changing the history in the public remote repositories, I will take a deep breath first.

If anyone does something before I do, please state here.

**Comment by johnnychen94** [comment]
Since e8dc970 is a simple commit, I believe a force-push from your latest branch is sufficient. And then remake a commit for e8dc970 and reauthor it, or just leave it to @cormullion :D

But before force-push, you can show your `git log` results here so that others can check if there's anything missed.

**Comment by cormullion** [comment]
I’m stuck on my iPhone for a while now, so I probably wont be touching anything here... (I know there are apps, but I don't want to practice on this... 😀)

**Comment by kimikage** [comment]
Oh, I have already merged e8dc970. I think I think I'm ready to `push -f`.
```diff
$ git diff 0890b41
diff --git a/docs/make.jl b/docs/make.jl
index fa481be..50229b7 100644
--- a/docs/make.jl
+++ b/docs/make.jl
@@ -14,7 +14,7 @@ makedocs(
     clean = false,
     modules = [Colors],
     format = Documenter.HTML(prettyurls = get(ENV, "CI", nothing) == "true",
-                             assets = ["assets/resize_svg.js"]),
+                             assets = ["assets/resize_svg.js", "assets/favicon.ico"]),
     sitename = "Colors",
     pages    = Any[
         "Introduction"             => "index.md",
diff --git a/docs/src/assets/favicon.ico b/docs/src/assets/favicon.ico
new file mode 100755
index 0000000..327e77f
Binary files /dev/null and b/docs/src/assets/favicon.ico differ
```
```
$ git log
commit f7c605f7d1cedd9b0a5ba401b404495eeda8b75e (HEAD)
Author: cormullion <cormullion@mac.com>
Date:   Thu Jan 2 10:13:21 2020 +0000

    favicon.ico added

commit 0890b410940fa9645496a394e5c449ef7104769a (origin/master, master)
Author: kimikage <kimikage.ceo@gmail.com>
Date:   Tue Dec 31 05:06:17 2019 +0900

    Remove JLD2 dependency (#389)

commit 9a443dc080b9a358b0eafa229bf4f6a2c570fc74
Author: Tim Holy <tim.holy@gmail.com>
Date:   Mon Dec 30 11:14:53 2019 -0600

    Speed up grayscale conversion (#391)

commit 5d077b35405730e76578a9bfe1fe4614fad8adcb (tag: v0.11.1)
Author: kimikage <kimikage.ceo@gmail.com>
Date:   Tue Dec 31 02:14:13 2019 +0900

    Version 0.11.1 (#392)
```

**Comment by johnnychen94** [comment]
Great, if there aren't any more commits between 0890b410940fa9645496a394e5c449ef7104769a and f7c605f7d1cedd9b0a5ba401b404495eeda8b75e , then a force-push makes everything back. My memory says that's all the commits.

**Comment by kimikage** [comment]
I'm sorry, but I realized that I cannot push to a protected branch.
@timholy,I need your help.

**Comment by timholy** [comment]
Oh dear, so sorry I screwed it up. (I am not sure how that happened.) I just changed the setting to allow forced pushes to protected branches, so go for it. We will want to turn it off again once fixed.

**Comment by kimikage** [comment]
Probably fixed.
And, we need to rebuild the docs.

**Comment by johnnychen94** [comment]
This becomes a relax to my heavy daily work LOL

**Comment by cormullion** [comment]
Sorry again!
