### ISSUE TITLE
`DomainError` needs a val argument.

### ISSUE THREAD

**Issue by rafaqz** [JuliaGraphics/Colors.jl#416]
https://github.com/JuliaGraphics/Colors.jl/blob/a447509004d10099b8ee4445dfdb8fdc097dec61/src/utilities.jl#L208

https://github.com/JuliaGraphics/Colors.jl/blob/a447509004d10099b8ee4445dfdb8fdc097dec61/src/utilities.jl#L212

**Comment by kimikage** [comment]
BTW, are the following valid?
```julia
weighted_color_mean(w1, Gray{Bool}(0), Gray{Bool}(0))
weighted_color_mean(w1, Gray{Bool}(1), Gray{Bool}(1))
weighted_color_mean(0, gray_bool1, gray_bool2)
weighted_color_mean(1, gray_bool1, gray_bool2)
```

**Comment by kimikage** [comment]
The `DomainError` is necessary only for `w1`, and I think that we should throw `InexactError` for values ​​other than `0`/`1`. So, my idea is:
```julia
function _weighted_color_mean(w1::Real, c1::Colorant, c2::Colorant)
    w1 < zero(w1) || w1 > oneunit(w1) && throw(DomainError(w1, "`w1` must be in [0, 1]"))
    w2 = oneunit(w1) - w1
    T = promote_type(eltype(c1), eltype(c2))
    mapc((x, y)->convert(T, muladd(w1, x, w2 * y)), c1, c2)
end
function _weighted_color_mean(w1::Integer, c1::C, c2::C) where C <: Colorant
    w1 < zero(w1) || w1 > oneunit(w1) && throw(DomainError(w1, "`w1` must be in [0, 1]"))
    w1 == zero(w1) ? c2 : c1
end
```

However, in the current implementation, the type of the weight (`w1`) will be converted.:confused:
https://github.com/JuliaGraphics/Colors.jl/blob/0b7f76ca53a3a0f5899b757a543990577d4c1248/src/utilities.jl#L211
The code was introduced in PR #253. Can anyone explain the reason for this?
cc: @hofmannmartin, @timholy
