### ISSUE TITLE
[RFC] Stopping use of depwarn intended to inform to "end users"

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#419]
In Julia v1.5 series (or nightly build),
> * Deprecation warnings are no longer shown by default. i.e. if the `--depwarn=...` flag is not passed it defaults to `--depwarn=no`.

cf. https://github.com/JuliaLang/julia/pull/35362

Therefore, depwarns will be for package developers, not for end users. (We use depwarn instead of normal warn just because it's annoying.:sweat:)

There are 4 depwarns used in this package.

## Base.hex
https://github.com/JuliaGraphics/Colors.jl/blob/a447509004d10099b8ee4445dfdb8fdc097dec61/src/utilities.jl#L103-L106
Perhaps the end users won't explicitly specify `Base`, so we can leave this. (We can also remove this.)

## hex
https://github.com/JuliaGraphics/Colors.jl/blob/a447509004d10099b8ee4445dfdb8fdc097dec61/src/utilities.jl#L109-L116
This is a problem as the new behavior will not involve any API changes. Also, `hex` is a function used directly by the end users. However, I don't think we need to show this depwarn to the end user when Julia v1.5 is released. So, we can leave this.

## ColorTypes.color
https://github.com/JuliaGraphics/Colors.jl/blob/f1047dafb88f72ef242cfc71b6358b9460562835/src/parse.jl#L225-L228
This is a proper use case of depwarn, but I don't think it's necessary anymore. Moreover, `color` is defined in ColorTypes and exported (and re-exported).

## parse
https://github.com/JuliaGraphics/Colors.jl/blob/f1047dafb88f72ef242cfc71b6358b9460562835/src/parse.jl#L143-L147

This has been a problem since the beginning. (cf. https://github.com/JuliaGraphics/Colors.jl/pull/390)
This is mainly for end users, so it doesn't make sense if it disappears. At least this is what should be displayed as a normal warn.

**Comment by kimikage** [comment]
This is off-topic but I don't understand CI failures on nightly build.
```julia
Parse: Log Test Failed at /home/travis/build/JuliaGraphics/Colors.jl/test/parse.jl:17
  Expression: parse(Colorant, "sea GREEN")
  Log Pattern: (:warn, r"Use \"SeaGreen\" or \"seagreen\"")
  Captured Logs: 
```
`Pkg.test` uses `--depwarn=yes` now (cf. https://github.com/JuliaLang/Pkg.jl/pull/1763).

**Comment by johnnychen94** [comment]
This is becoming too nitpicking and seems like an antipattern wrt JuliaLang/julia#35362

End-users don't read warnings. They don't even read error messages. Since the old API works fine, he could choose to not update his API accordingly, why must he see these warnings even if he set Compat correctly wrt semver?

The new practice after JuliaLang/julia#35362, IIUC, is to switch on the depwarn option when you try to add a new breaking version in compact and then fix all depwarns in one PR.

**Comment by kimikage** [comment]
> End-users don't read warnings. They don't even read error messages.

Indeed. Similarly, package developers do not read the commit logs or release notes. :stuck_out_tongue:

**Comment by kimikage** [comment]
I'm thinking of removing the depwarn in `parse`. For the time being, I do not intend to ban the names with spaces. [The document](http://juliagraphics.github.io/Colors.jl/stable/constructionandconversion/#Base.parse) has already stated that they are not recommended. (Some users do not read the document, though. :stuck_out_tongue:)

**Comment by kimikage** [comment]
Gotcha! I think we were not on the same wavelength because of my poor English, @johnnychen94.

**Comment by kimikage** [comment]
Let's discuss the depwarns in separate PRs.
