### ISSUE TITLE
hex() doesn't support Gray{Bool}

### ISSUE THREAD

**Issue by Kaduo** [JuliaGraphics/Colors.jl#428]
I noticed this because Juno throws an error at me when it tries to display a Gray{Bool} pixel. I'm trying to understand the hex() code a bit more before attempting a fix, but I assume this shouldn't be too complicated.

**Comment by kimikage** [comment]
I'm sorry. This is my oversight.
```julia
julia> hex(Gray{Bool}(1))
ERROR: MethodError: no method matching clamp01(::Bool)
```
As the error message suggests, adding `Bool` to `Union` should make it work.
https://github.com/JuliaGraphics/Colors.jl/blob/377ffcec0c3c56fa13b8c6cf5b5ad725caec44d7/src/utilities.jl#L37

**Comment by kimikage** [comment]
I will send a minimal PR and release v0.12.2.

> but I assume this shouldn't be too complicated.

What does "this" mean? The implementation of `hex`? Or the issue/fix?

**Comment by Kaduo** [comment]
Thanks for fixing it so quickly!

 > > but I assume this shouldn't be too complicated.
> 
> What does "this" mean? The implementation of `hex`? Or the issue/fix?

I meant the issue/fix, why?

**Comment by kimikage** [comment]
I'm just concerned that the current implementation of `hex` is hard to understand. :smile:
