### ISSUE TITLE
Stopping forced conversion of  weight type in `weighted_color_mean`

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#430]
I plan to remove the following type conversion with the next v0.13.
https://github.com/JuliaGraphics/Colors.jl/blob/53c2acb9c4ac4aa16f9de036a1a96b36a86ce924/src/utilities.jl#L209

See https://github.com/JuliaGraphics/Colors.jl/issues/416#issuecomment-619586809 and PR #421.

**Comment by kimikage** [comment]
BTW, I find it not intuitive that the weight argument is `w1` instead of `w2`. Should we add a variant with `w1` and `w2` keyword arguments?

**Comment by timholy** [comment]
I support removal. I don't understand the `w1` instead of `w2` part.

**Comment by kimikage** [comment]
```julia
weighted_color_mean(0, colorant"red", colorant"blue") == colorant"blue"
```
Since the primary axis usually directed right, I think it is more intuitive for `weight = 0` to be "red" and `weight = 1` to be "blue".

My proposal is to add a new method as follows:
```julia
julia> weighted_color_mean(colorant"red", colorant"blue", w1=0) # w2 = 1
RGB{N0f8}(0.0,0.0,1.0)

julia> weighted_color_mean(colorant"red", colorant"blue", w2=0) # w1 = 1
RGB{N0f8}(1.0,0.0,0.0)

julia> weighted_color_mean(colorant"red", colorant"blue", w1=0.6, w2=0.4) # this is useful, but is it a troublemaker?
RGB{N0f8}(0.6,0.0,0.4)
```

**Comment by timholy** [comment]
I'm not sure I like that, as you say it adds a troublesome check and to me seems to increase the cognitive load. 

I read the original statement as "0 parts red and 1 part blue," which to me is pretty intuitive. Writing it out manually as `(1-w)*c1 + w*c2` and not having a function at all has a certain appeal---it's very clear what's happening---but there are reasons we don't support that. I don't see an option that's equally clear, though.

If memory serves I did not write these, and in any event I am not terribly invested in the final outcome here, just letting you know my own impressions.

**Comment by kimikage** [comment]
I don't like the current counter-intuitive implementation, but I don't intend to eliminate it.

I would like to refactor the `colormap` in the near future.
https://github.com/JuliaGraphics/Colors.jl/blob/90cab753d53fabd021ba0215fa9d92643708b20b/src/colormaps.jl#L145-L147
Sigh. :confused:

**Comment by timholy** [comment]
You can never have too many functions that do exactly the same thing.

**Comment by timholy** [comment]
Maybe we could autogenerate them:
```julia
for i = 1:100
    fname = Symbol(randstring(8))
    args = [:(a::Colorant), :(b::Colorant), :(w::Real)]
    argorder = randperm(3)
    @eval begin
        $fname($(args[argorder]...)) = ...
    end
end
```
