### ISSUE TITLE
colordiff not work with all colors?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Colors.jl#437]
Just wondering why `colordiff` doesn't work with all colors?

```
julia> using Colors
julia> colordiff(RGBA(0.35, 0.18, 0.90, 1), RGBA(0.34, 0.18, 0.90, 1))
ERROR: MethodError: no method matching colordiff(::RGBA{Float64}, ::RGBA{Float64})
Stacktrace:
 [1] top-level scope at none:1
```

There's probably a good reason, but I'm interested to know what it is. 

Colors v0.12.3, Julia 1.5.0

**Comment by johnnychen94** [comment]
This could print thousands of warnings if it's an image...

**Comment by michel-leonard** [comment]
[Here](https://github.com/michel-leonard/ciede2000-color-matching/tree/main/tests/jl#%CE%B4e2000--accurate-fast-julia-powered), in the public domain, is a CIE **ΔE2000** function written in Julia, reliable and accurate.
