### ISSUE TITLE
configure SSH key for TagBot and optionally for CompatHelper

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/Colors.jl#443]
I tried to not notify anyone with a direct commit c88f062 but it doesn't work...

Here's the motivation: 

One GitHub action could not trigger another GitHub action if only configured with `token: ${{ secrets.GITHUB_TOKEN }}`. This limitation means, PR created by CompatHelper could not trigger the unit test, and release/tag created by tagbot could trigger the docs CI, which is switched to GH in #433 .

The ssh key for tagbot seems a necessary step. Though the ssh key for compat helper could be skipped given that we still need to manually check the versions even if the unit test runs.

For TagBot, the quick command to generate ssh key:

```
ssh-keygen -t rsa -b 4096 -C "email@example.com" -f tagbot
```

then copy `tagbot.pub` as keys and `tagbot` as secrets (let's say with name "TagBot"). A commit like https://github.com/JuliaImages/ImageEdgeDetection.jl/commit/bd6515ae2bb6a88842cc07fd6abf1ea40231d6bd should then set things done. (Haven't checked it because there's no new releases...)

References:

- https://github.com/JuliaRegistries/CompatHelper.jl#12-set-up-the-ssh-deploy-key-optional
- https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions

cc: @cormullion @timholy

**Comment by timholy** [comment]
Thanks for the hand-holding, really appreciate it!
