### ISSUE TITLE
Unsatisfiable requirements detected on Julia 1.0

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaGraphics/Colors.jl#450]
I'm trying to fix a breaking CI for Julia 1.0 at Gadfly (https://github.com/GiovineItalia/Gadfly.jl/pull/1496). So far, it is quite a mess, but I think I now have pinned it down to the following:

```
ERROR: Unsatisfiable requirements detected for package Cairo [159f3aea]:
   Cairo [159f3aea] log:
   ├─possible versions are: [0.5.3-0.5.6, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.5] or uninstalled
   ├─restricted to versions [0.7.0-0.7, 0.8.0-0.8, 1.0.0-1] by an explicit requirement, leaving only versions [0.7.0, 0.8.0, 1.  0.0-1.0.5]
   ├─restricted by julia compatibility requirements to versions: [0.5.3-0.5.6, 0.6.0, 0.7.0, 0.8.0] or uninstalled, leaving onl  y versions: [0.7.0, 0.8.0]
   └─restricted by compatibility requirements with Colors [5ae59095] to versions: 1.0.3-1.0.5 or uninstalled — no versions left
     └─Colors [5ae59095] log:
       ├─possible versions are: [0.9.0, 0.9.2-0.9.6, 0.10.0-0.10.2, 0.11.0-0.11.2, 0.12.0-0.12.4] or uninstalled
       ├─restricted to versions [0.9.0-0.9, 0.10.0-0.10, 0.11.0-0.11, 0.12.0-0.12] by Gadfly [c91e804a], leaving only versions   [0.9.0, 0.9.2-0.9.6, 0.10.0-0.10.2, 0.11.0-0.11.2, 0.12.0-0.12.4]
       │ └─Gadfly [c91e804a] log:
       │   ├─possible versions are: 1.3.1 or uninstalled
       │   └─Gadfly [c91e804a] is fixed to version 1.3.1
       └─restricted to versions 0.12.4 by an explicit requirement, leaving only versions 0.12.4
```

Which shows that `Cairo` is restricted to at most 0.8. However, I don't see how it is linked to Colors at https://github.com/JuliaGraphics/Cairo.jl/blob/v0.8.0/Project.toml.

**Comment by johnnychen94** [comment]
> Which shows that Cairo is restricted to at most 0.8. However, I don't see how it is linked to Colors at https://github.com/JuliaGraphics/Cairo.jl/blob/v0.8.0/Project.toml.

You need to either:

- [update General/Cairo registry](https://github.com/JuliaRegistries/General/blob/d666c59a03a374e292e18f5e67350518aa64b913/C/Cairo/Compat.toml#L1-L2). It was set to the latest available Colors version because the Project.toml file in Cairo@0.8 doesn't set a upper bound for Colors.
- make a v0.8 branch for Cairo, updates the compatibility, and tag Cairo@0.8.1

There's nothing we could do here in Colors because it's Cairo that gets outdated.

**Comment by rikhuijzer** [comment]
Aha, so that is it! Many thanks
