### ISSUE TITLE
Linking colours to palette

### ISSUE THREAD

**Issue by joseph-pollacco** [JuliaGraphics/Colors.jl#454]
Hi,

Thanks for proposing such a beautiful colour palette. As in my Remarque:
https://discourse.julialang.org/t/plots-juliagraphics-colors-jl-removing-the-guess-of-colours/50010

We propose that you link your page with:
http://juliagraphics.github.io/Colors.jl/stable/namedcolors/

As one can see the true colours.

Cheers,
joseph

**Comment by timholy** [comment]
I'm not sure what this is asking. Is there a link missing?

**Comment by kimikage** [comment]
Did you mean: https://discourse.julialang.org/t/plots-juliagraphics-colors-jl-removing-the-guess-of-colours/50010/9
