### ISSUE TITLE
[Request] Allow for more than two colors in `weighted_color_mean`.

### ISSUE THREAD

**Issue by cjwyett** [JuliaGraphics/Colors.jl#467]

**Comment by kimikage** [comment]
What kind of interface would you like to have?
For example, does it look something like this?
```julia
weighted_color_mean(w::AbstractVector{<:Real}, colors::AbstractVector{<:Colorant})
```

FWIW, this could not apply well to color types with hue (e.g. `HSV`).

**Comment by cjwyett** [comment]
Absolutely spot on with that example, being able to input a vectors would be extremely useful.
