### ISSUE TITLE
is `inv` on Colors well defined? 

### ISSUE THREAD

**Issue by anandijain** [JuliaGraphics/Colors.jl#488]
`Base.inv(p::RGB) = RGB(1 - p.r, 1 - p.g, 1 - p.b)`

I was trying to mess around with some of the common filters like inverting the colors, and it seems this would be well defined.

Also, I think this one allocates, so avoiding that would be nice

Is there a reason to not want to overload `inv`? would also want to generalize it to more than just RGB (its just the one I'm familiar with)

this would make it really easy to then take an image and just `inv.(img)` and get that classic "invert colors" effect

**Comment by anandijain** [comment]
also I don't know how one could avoid floating point errors from double inverts
```julia 
julia> dump(inv(inv(purp)) - purp)
RGB{Float64}
  r: Float64 0.0
  g: Float64 -2.7755575615628914e-17
  b: Float64 0.0
```

**Comment by johnnychen94** [comment]
> Is there a reason to not want to overload inv?

From `?inv`, it is required to satisfy `inv(x) * x == x * inv(x) == one(x)` so clearly that `inv(x::Real) = one(x) - x` doesn't satisfy this property. Hence we can't overload `Base.inv` function. We might introduce a new function, e.g., `invert_color`.

> I was trying to mess around with some of the common filters like inverting the colors, and it seems this would be well defined.

This concept is more like a "mirror" operation and might only be well defined for "linear" color space such as `RGB`, `XYZ`. For non-linear color space such as `Lab`, I don't know, it might be sufficient to only invert the `L` channel.

**Comment by anandijain** [comment]
Thanks, yes I was worried about the roundoff error. This is helpful, I know really little about color spaces. Is there a type specifically for the Linear spaces so that invert_color could be extended?

```julia 
julia> dump(inv(inv(purp)) - purp)
RGB{Float64}
  r: Float64 0.0
  g: Float64 -2.7755575615628914e-17
  b: Float64 0.0
```

It's not a big deal to not have this, since it is so easy to write. I was mainly just curious

**Comment by kimikage** [comment]
FYI, you can use `ColorVectorSpace.complement` (formerly [`Images.complement`](https://juliaimages.org/v0.22/function_reference/#Images.complement)) for `AbstractRGB`.
See also the second half of https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/125#discussion_r389423431.

**Comment by kimikage** [comment]
Anyway, since `inv` is no longer a topic of this discussion, I think it would be better to change the subject of this issue or open a new issue.

I have no objection to adding the functionality to get the complementary "color" (not "numbers"), but I don't think we should introduce our own definition for it. We should refer to papers or well-known tools on color science or image processing.
