### ISSUE TITLE
What should `default_brettel_neutral` be?

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/Colors.jl#502]
`default_brettel_neutral` is used as a reference value in the simulation of color deficiency.
https://github.com/JuliaGraphics/Colors.jl/blob/f38f27caa31c428902fd2974dda657a117171278/src/algorithms.jl#L63-L65

Since sRGB has a white point of D65, this looks more straightforward with `convert(LMS, WP_D65)`.
However, why is `WP_D65` used instead of `WP_E` (equal-energy)?

If we change it, it may affect the default color scheme of Gadfly etc. Therefore, rather than change the behavior, I would like to make the third argument of `protanopic` etc. a public API and make the documentation explicit.

cc: @dcjones
https://github.com/GiovineItalia/Compose.jl/commit/9c3a046076eb55883538dd87e614a957183d91f9

**Comment by dcjones** [comment]
It probably should be `WP_E`, and I just didn't quite know what I was doing when I wrote that.

Changing it does affect Gadfly's default color scheme, but I don't find the change to be bad per se.

Here's what the change looks like, if anyone cares to disagree:
![image](https://user-images.githubusercontent.com/210361/126678801-cffdaab5-57a0-4f2c-bd92-daec8b6b138b.png)
