### ISSUE TITLE
in the README, put a link on the home page

### ISSUE THREAD

**Issue by jabbalaci** [JuliaGraphics/Colors.jl#516]
In the README, please put a link to the home page of the project: https://juliagraphics.github.io/Colors.jl/stable/ .

**Comment by johnnychen94** [comment]
![image](https://user-images.githubusercontent.com/8684355/139581122-da95b801-0e79-46e0-bef1-c2e6b2f95e76.png)

**Comment by jabbalaci** [comment]
OK, thanks. I was reading just the text.
