### ISSUE TITLE
Release v0.13?

### ISSUE THREAD

**Issue by chrisbrahms** [JuliaGraphics/Colors.jl#524]
Hi,

I want to calculate the weighted sum of an array of colours to convert a spectrum to perceived colour using `colormatch`. As far as I can see, `weighted_color_mean` supports this functionality on master. The compat note says that this requires Colors.jl v0.13, but no such version exists. Would it be possible to release v0.13 with this addition? 
https://github.com/JuliaGraphics/Colors.jl/blob/b550b7bc2f6f27fdf61c30b3215b28df826ceebf/src/utilities.jl#L516

Thanks!

**Comment by johnnychen94** [comment]
We can make a release any time (together with ColorTypes v0.12), but both are breaking changes, and we don't have volunteers to test them out around and make potential fixes. Both @timholy and me are busy these days and might not have the bandwidth to proceed this.

In other words, we're looking for active maintainers for ColorTypes, Colors and ColorVectorSpaces 👀

**Comment by kimikage** [comment]
I had to leave the development a few years ago due to somewhat misfortunes. I apologize for the inconvenience.

I am now cleaning up my messes of the past, but this does not mean my "resurrection”.
I am in relatively good health now and need not worry about that. But the circumstances surrounding me are certainly harsher than a few years ago.

So, we're still looking for active maintainers.

**Comment by ViralBShah** [comment]
Help to update and tag/release the packages with some of the breaking changes is much appreciated. We just tagged ColorTypes 0.12, and Colors.jl should also get released along with that.

The main reason (for me) for getting the releases done is to remove the deprecated bindings messages across the various Images packages and also to be able to use some of the newer versions of ImageMagick and such. 

It would be great to have new maintainers step up.

**Comment by ViralBShah** [comment]
Tagging 0.13.0 https://github.com/JuliaRegistries/General/pull/117836
