### ISSUE TITLE
BGR interpreted as RGB

### ISSUE THREAD

**Issue by tawheeler** [JuliaGraphics/Colors.jl#532]
Maybe I'm missing something, but the following behavior for BGR was unexpected:

```
> c = RGB(0.0, 0.5, 1.0); c.r
0.0
> d = BGR(0.0, 0.5, 1.0); d.r
0.0
```

I would have expected BGR to set its red channel to 1.0, but it appears to also be using the RGB ordering.

**Comment by timholy** [comment]
See the bold text in https://github.com/JuliaGraphics/ColorTypes.jl#rgb-plus-bgr-xrgb-rgbx-and-rgb24-the-abstractrgb-group. This is a debatable design decision but it allows generic programming without needing to know or care about the specific memory layout.
