### ISSUE TITLE
Dark Mode on website makes it nearly-impossible to see names on the namedcolors page

### ISSUE THREAD

**Issue by chipbuster** [JuliaGraphics/Colors.jl#554]
I was visiting https://juliagraphics.github.io/Colors.jl/stable/namedcolors/ and wondering why there were no color names on the swatches, since I distinctly remembered being able to get color names from here in the past.

However, after some scoping around, I realized that the color names were there, they were just illegible because the site had been placed in dark mode!

![image](https://github.com/JuliaGraphics/Colors.jl/assets/4605384/bce7f0b8-1a08-4ec6-9024-3f85a34c15f0)

It would be nice if the names could be rendered in white or very light gray when the page is in dark mode, though I appreciate that this might be trickier than it sounds.

**Comment by kimikage** [comment]
This is due to a change in the behavior of Documenter.jl.
For the time being, please refer to the dev version of the documentation.
https://juliagraphics.github.io/Colors.jl/dev/namedcolors/

**Comment by kimikage** [comment]
Fixed by #555
https://juliagraphics.github.io/Colors.jl/v0.12/namedcolors/
